// generated by scripts/gen_vim_binding_tests.swift from Sources/ItsyKeymap/Resources/keys.vim.toml. do not edit.
import AppKit
import ItsyKeymap
import ItsyVim
import Testing

private let generatedVimBindingCases: [GeneratedVimBindingCase] = [
	GeneratedVimBindingCase(line: 2, mode: .global, key: "Cmd-Z", commandID: "edit.undo"),
	GeneratedVimBindingCase(line: 3, mode: .global, key: "Cmd-Shift-Z", commandID: "edit.redo"),
	GeneratedVimBindingCase(line: 4, mode: .global, key: "Cmd-X", commandID: "edit.cut"),
	GeneratedVimBindingCase(line: 5, mode: .global, key: "Cmd-C", commandID: "edit.copy"),
	GeneratedVimBindingCase(line: 6, mode: .global, key: "Cmd-V", commandID: "edit.paste"),
	GeneratedVimBindingCase(line: 7, mode: .global, key: "Cmd-A", commandID: "edit.selectAll"),
	GeneratedVimBindingCase(line: 8, mode: .global, key: "Cmd-S", commandID: "file.save"),
	GeneratedVimBindingCase(line: 9, mode: .global, key: "Cmd-Shift-S", commandID: "file.saveAs"),
	GeneratedVimBindingCase(line: 10, mode: .global, key: "Cmd-N", commandID: "file.new"),
	GeneratedVimBindingCase(line: 11, mode: .global, key: "Cmd-O", commandID: "file.open"),
	GeneratedVimBindingCase(line: 12, mode: .global, key: "Cmd-W", commandID: "pane.close"),
	GeneratedVimBindingCase(line: 13, mode: .global, key: "Cmd-Q", commandID: "app.quit"),
	GeneratedVimBindingCase(line: 14, mode: .global, key: "Cmd-F", commandID: "edit.find"),
	GeneratedVimBindingCase(line: 15, mode: .global, key: "Cmd-G", commandID: "edit.findNext"),
	GeneratedVimBindingCase(line: 16, mode: .global, key: "Cmd-Shift-G", commandID: "edit.findPrevious"),
	GeneratedVimBindingCase(line: 17, mode: .global, key: "Cmd-,", commandID: "app.settings"),
	GeneratedVimBindingCase(line: 18, mode: .global, key: "Cmd-Shift-P", commandID: "view.commandPalette"),
	GeneratedVimBindingCase(line: 19, mode: .global, key: "Cmd-P", commandID: "nav.gotoFile"),
	GeneratedVimBindingCase(line: 20, mode: .global, key: "Cmd-B", commandID: "view.sidebar.toggle"),
	GeneratedVimBindingCase(line: 21, mode: .global, key: "Cmd-J", commandID: "terminal.toggle"),
	GeneratedVimBindingCase(line: 22, mode: .global, key: "Cmd-Shift-N", commandID: "file.newWindow"),
	GeneratedVimBindingCase(line: 23, mode: .global, key: "Cmd-Shift-F", commandID: "edit.findInProject"),
	GeneratedVimBindingCase(line: 24, mode: .global, key: "Cmd-D", commandID: "editor.addNextSelection"),
	GeneratedVimBindingCase(line: 25, mode: .global, key: "Cmd-Ctrl-G", commandID: "edit.selectAllFindMatches"),
	GeneratedVimBindingCase(line: 26, mode: .global, key: "Cmd-T", commandID: "nav.gotoSymbolWorkspace"),
	GeneratedVimBindingCase(line: 27, mode: .global, key: "Cmd-Shift-O", commandID: "nav.gotoSymbolFile"),
	GeneratedVimBindingCase(line: 28, mode: .global, key: "Ctrl-G", commandID: "nav.gotoLine"),
	GeneratedVimBindingCase(line: 29, mode: .global, key: "Ctrl-Tab", commandID: "file.nextBuffer"),
	GeneratedVimBindingCase(line: 30, mode: .global, key: "Ctrl-Shift-Tab", commandID: "file.previousBuffer"),
	GeneratedVimBindingCase(line: 31, mode: .global, key: "Cmd-1", commandID: "file.selectTab.1"),
	GeneratedVimBindingCase(line: 32, mode: .global, key: "Cmd-2", commandID: "file.selectTab.2"),
	GeneratedVimBindingCase(line: 33, mode: .global, key: "Cmd-3", commandID: "file.selectTab.3"),
	GeneratedVimBindingCase(line: 34, mode: .global, key: "Cmd-4", commandID: "file.selectTab.4"),
	GeneratedVimBindingCase(line: 35, mode: .global, key: "Cmd-5", commandID: "file.selectTab.5"),
	GeneratedVimBindingCase(line: 36, mode: .global, key: "Cmd-6", commandID: "file.selectTab.6"),
	GeneratedVimBindingCase(line: 37, mode: .global, key: "Cmd-7", commandID: "file.selectTab.7"),
	GeneratedVimBindingCase(line: 38, mode: .global, key: "Cmd-8", commandID: "file.selectTab.8"),
	GeneratedVimBindingCase(line: 39, mode: .global, key: "Cmd-9", commandID: "file.selectTab.9"),
	GeneratedVimBindingCase(line: 40, mode: .global, key: "Cmd-\\", commandID: "pane.splitHorizontal"),
	GeneratedVimBindingCase(line: 41, mode: .global, key: "Cmd-Opt-\\", commandID: "pane.splitVertical"),
	GeneratedVimBindingCase(line: 42, mode: .global, key: "Cmd-Opt-Left", commandID: "pane.focusLeft"),
	GeneratedVimBindingCase(line: 43, mode: .global, key: "Cmd-Opt-Right", commandID: "pane.focusRight"),
	GeneratedVimBindingCase(line: 44, mode: .global, key: "Cmd-Opt-Up", commandID: "pane.focusUp"),
	GeneratedVimBindingCase(line: 45, mode: .global, key: "Cmd-Opt-Down", commandID: "pane.focusDown"),
	GeneratedVimBindingCase(line: 46, mode: .global, key: "Cmd-K Cmd-S", commandID: "app.keyboardShortcuts"),
	GeneratedVimBindingCase(line: 49, mode: .normal, key: "h", commandID: "editor.moveLeft"),
	GeneratedVimBindingCase(line: 50, mode: .normal, key: "j", commandID: "editor.moveDown"),
	GeneratedVimBindingCase(line: 51, mode: .normal, key: "k", commandID: "editor.moveUp"),
	GeneratedVimBindingCase(line: 52, mode: .normal, key: "l", commandID: "editor.moveRight"),
	GeneratedVimBindingCase(line: 53, mode: .normal, key: "Left", commandID: "editor.moveLeft"),
	GeneratedVimBindingCase(line: 54, mode: .normal, key: "Right", commandID: "editor.moveRight"),
	GeneratedVimBindingCase(line: 55, mode: .normal, key: "Up", commandID: "editor.moveUp"),
	GeneratedVimBindingCase(line: 56, mode: .normal, key: "Down", commandID: "editor.moveDown"),
	GeneratedVimBindingCase(line: 57, mode: .normal, key: "w", commandID: "editor.moveWordForward"),
	GeneratedVimBindingCase(line: 58, mode: .normal, key: "Shift-W", commandID: "editor.moveBigWordForward"),
	GeneratedVimBindingCase(line: 59, mode: .normal, key: "b", commandID: "editor.moveWordBackward"),
	GeneratedVimBindingCase(line: 60, mode: .normal, key: "Shift-B", commandID: "editor.moveBigWordBackward"),
	GeneratedVimBindingCase(line: 61, mode: .normal, key: "e", commandID: "editor.moveWordEnd"),
	GeneratedVimBindingCase(line: 62, mode: .normal, key: "Shift-E", commandID: "editor.moveBigWordEnd"),
	GeneratedVimBindingCase(line: 63, mode: .normal, key: "0", commandID: "editor.moveLineStart"),
	GeneratedVimBindingCase(line: 64, mode: .normal, key: "Shift-6", commandID: "editor.moveLineStart"),
	GeneratedVimBindingCase(line: 65, mode: .normal, key: "Shift-4", commandID: "editor.moveLineEnd"),
	GeneratedVimBindingCase(line: 66, mode: .normal, key: "gg", commandID: "editor.moveBufferStart"),
	GeneratedVimBindingCase(line: 67, mode: .normal, key: "Shift-G", commandID: "editor.moveBufferEnd"),
	GeneratedVimBindingCase(line: 68, mode: .normal, key: "Shift-[", commandID: "editor.moveParagraphBackward"),
	GeneratedVimBindingCase(line: 69, mode: .normal, key: "Shift-]", commandID: "editor.moveParagraphForward"),
	GeneratedVimBindingCase(line: 70, mode: .normal, key: "f", commandID: "editor.findCharForward"),
	GeneratedVimBindingCase(line: 71, mode: .normal, key: "Shift-F", commandID: "editor.findCharBackward"),
	GeneratedVimBindingCase(line: 72, mode: .normal, key: "t", commandID: "editor.tillCharForward"),
	GeneratedVimBindingCase(line: 73, mode: .normal, key: "Shift-T", commandID: "editor.tillCharBackward"),
	GeneratedVimBindingCase(line: 74, mode: .normal, key: ";", commandID: "editor.repeatCharFind"),
	GeneratedVimBindingCase(line: 75, mode: .normal, key: ",", commandID: "editor.repeatCharFindReverse"),
	GeneratedVimBindingCase(line: 76, mode: .normal, key: "d", commandID: "vim.operator.delete"),
	GeneratedVimBindingCase(line: 77, mode: .normal, key: "c", commandID: "vim.operator.change"),
	GeneratedVimBindingCase(line: 78, mode: .normal, key: "y", commandID: "vim.operator.yank"),
	GeneratedVimBindingCase(line: 79, mode: .normal, key: "Shift-'", commandID: "vim.registerPrefix"),
	GeneratedVimBindingCase(line: 80, mode: .normal, key: "Ctrl-O", commandID: "vim.jumpOlder"),
	GeneratedVimBindingCase(line: 81, mode: .normal, key: "Ctrl-I", commandID: "vim.jumpNewer"),
	GeneratedVimBindingCase(line: 82, mode: .normal, key: "gd", commandID: "lsp.definition"),
	GeneratedVimBindingCase(line: 83, mode: .normal, key: "g Shift-D", commandID: "lsp.declaration"),
	GeneratedVimBindingCase(line: 84, mode: .normal, key: "gf", commandID: "file.openUnderCursor"),
	GeneratedVimBindingCase(line: 85, mode: .normal, key: "gt", commandID: "file.nextBuffer"),
	GeneratedVimBindingCase(line: 86, mode: .normal, key: "g Shift-T", commandID: "file.previousBuffer"),
	GeneratedVimBindingCase(line: 87, mode: .normal, key: "''", commandID: "vim.jumpBack"),
	GeneratedVimBindingCase(line: 88, mode: .normal, key: "m a", commandID: "vim.mark.set.a"),
	GeneratedVimBindingCase(line: 89, mode: .normal, key: "m b", commandID: "vim.mark.set.b"),
	GeneratedVimBindingCase(line: 90, mode: .normal, key: "m c", commandID: "vim.mark.set.c"),
	GeneratedVimBindingCase(line: 91, mode: .normal, key: "m d", commandID: "vim.mark.set.d"),
	GeneratedVimBindingCase(line: 92, mode: .normal, key: "m e", commandID: "vim.mark.set.e"),
	GeneratedVimBindingCase(line: 93, mode: .normal, key: "m f", commandID: "vim.mark.set.f"),
	GeneratedVimBindingCase(line: 94, mode: .normal, key: "m g", commandID: "vim.mark.set.g"),
	GeneratedVimBindingCase(line: 95, mode: .normal, key: "m h", commandID: "vim.mark.set.h"),
	GeneratedVimBindingCase(line: 96, mode: .normal, key: "m i", commandID: "vim.mark.set.i"),
	GeneratedVimBindingCase(line: 97, mode: .normal, key: "m j", commandID: "vim.mark.set.j"),
	GeneratedVimBindingCase(line: 98, mode: .normal, key: "m k", commandID: "vim.mark.set.k"),
	GeneratedVimBindingCase(line: 99, mode: .normal, key: "m l", commandID: "vim.mark.set.l"),
	GeneratedVimBindingCase(line: 100, mode: .normal, key: "m m", commandID: "vim.mark.set.m"),
	GeneratedVimBindingCase(line: 101, mode: .normal, key: "m n", commandID: "vim.mark.set.n"),
	GeneratedVimBindingCase(line: 102, mode: .normal, key: "m o", commandID: "vim.mark.set.o"),
	GeneratedVimBindingCase(line: 103, mode: .normal, key: "m p", commandID: "vim.mark.set.p"),
	GeneratedVimBindingCase(line: 104, mode: .normal, key: "m q", commandID: "vim.mark.set.q"),
	GeneratedVimBindingCase(line: 105, mode: .normal, key: "m r", commandID: "vim.mark.set.r"),
	GeneratedVimBindingCase(line: 106, mode: .normal, key: "m s", commandID: "vim.mark.set.s"),
	GeneratedVimBindingCase(line: 107, mode: .normal, key: "m t", commandID: "vim.mark.set.t"),
	GeneratedVimBindingCase(line: 108, mode: .normal, key: "m u", commandID: "vim.mark.set.u"),
	GeneratedVimBindingCase(line: 109, mode: .normal, key: "m v", commandID: "vim.mark.set.v"),
	GeneratedVimBindingCase(line: 110, mode: .normal, key: "m w", commandID: "vim.mark.set.w"),
	GeneratedVimBindingCase(line: 111, mode: .normal, key: "m x", commandID: "vim.mark.set.x"),
	GeneratedVimBindingCase(line: 112, mode: .normal, key: "m y", commandID: "vim.mark.set.y"),
	GeneratedVimBindingCase(line: 113, mode: .normal, key: "m z", commandID: "vim.mark.set.z"),
	GeneratedVimBindingCase(line: 114, mode: .normal, key: "` a", commandID: "vim.mark.jump.a"),
	GeneratedVimBindingCase(line: 115, mode: .normal, key: "` b", commandID: "vim.mark.jump.b"),
	GeneratedVimBindingCase(line: 116, mode: .normal, key: "` c", commandID: "vim.mark.jump.c"),
	GeneratedVimBindingCase(line: 117, mode: .normal, key: "` d", commandID: "vim.mark.jump.d"),
	GeneratedVimBindingCase(line: 118, mode: .normal, key: "` e", commandID: "vim.mark.jump.e"),
	GeneratedVimBindingCase(line: 119, mode: .normal, key: "` f", commandID: "vim.mark.jump.f"),
	GeneratedVimBindingCase(line: 120, mode: .normal, key: "` g", commandID: "vim.mark.jump.g"),
	GeneratedVimBindingCase(line: 121, mode: .normal, key: "` h", commandID: "vim.mark.jump.h"),
	GeneratedVimBindingCase(line: 122, mode: .normal, key: "` i", commandID: "vim.mark.jump.i"),
	GeneratedVimBindingCase(line: 123, mode: .normal, key: "` j", commandID: "vim.mark.jump.j"),
	GeneratedVimBindingCase(line: 124, mode: .normal, key: "` k", commandID: "vim.mark.jump.k"),
	GeneratedVimBindingCase(line: 125, mode: .normal, key: "` l", commandID: "vim.mark.jump.l"),
	GeneratedVimBindingCase(line: 126, mode: .normal, key: "` m", commandID: "vim.mark.jump.m"),
	GeneratedVimBindingCase(line: 127, mode: .normal, key: "` n", commandID: "vim.mark.jump.n"),
	GeneratedVimBindingCase(line: 128, mode: .normal, key: "` o", commandID: "vim.mark.jump.o"),
	GeneratedVimBindingCase(line: 129, mode: .normal, key: "` p", commandID: "vim.mark.jump.p"),
	GeneratedVimBindingCase(line: 130, mode: .normal, key: "` q", commandID: "vim.mark.jump.q"),
	GeneratedVimBindingCase(line: 131, mode: .normal, key: "` r", commandID: "vim.mark.jump.r"),
	GeneratedVimBindingCase(line: 132, mode: .normal, key: "` s", commandID: "vim.mark.jump.s"),
	GeneratedVimBindingCase(line: 133, mode: .normal, key: "` t", commandID: "vim.mark.jump.t"),
	GeneratedVimBindingCase(line: 134, mode: .normal, key: "` u", commandID: "vim.mark.jump.u"),
	GeneratedVimBindingCase(line: 135, mode: .normal, key: "` v", commandID: "vim.mark.jump.v"),
	GeneratedVimBindingCase(line: 136, mode: .normal, key: "` w", commandID: "vim.mark.jump.w"),
	GeneratedVimBindingCase(line: 137, mode: .normal, key: "` x", commandID: "vim.mark.jump.x"),
	GeneratedVimBindingCase(line: 138, mode: .normal, key: "` y", commandID: "vim.mark.jump.y"),
	GeneratedVimBindingCase(line: 139, mode: .normal, key: "` z", commandID: "vim.mark.jump.z"),
	GeneratedVimBindingCase(line: 140, mode: .normal, key: "' a", commandID: "vim.mark.jumpLine.a"),
	GeneratedVimBindingCase(line: 141, mode: .normal, key: "' b", commandID: "vim.mark.jumpLine.b"),
	GeneratedVimBindingCase(line: 142, mode: .normal, key: "' c", commandID: "vim.mark.jumpLine.c"),
	GeneratedVimBindingCase(line: 143, mode: .normal, key: "' d", commandID: "vim.mark.jumpLine.d"),
	GeneratedVimBindingCase(line: 144, mode: .normal, key: "' e", commandID: "vim.mark.jumpLine.e"),
	GeneratedVimBindingCase(line: 145, mode: .normal, key: "' f", commandID: "vim.mark.jumpLine.f"),
	GeneratedVimBindingCase(line: 146, mode: .normal, key: "' g", commandID: "vim.mark.jumpLine.g"),
	GeneratedVimBindingCase(line: 147, mode: .normal, key: "' h", commandID: "vim.mark.jumpLine.h"),
	GeneratedVimBindingCase(line: 148, mode: .normal, key: "' i", commandID: "vim.mark.jumpLine.i"),
	GeneratedVimBindingCase(line: 149, mode: .normal, key: "' j", commandID: "vim.mark.jumpLine.j"),
	GeneratedVimBindingCase(line: 150, mode: .normal, key: "' k", commandID: "vim.mark.jumpLine.k"),
	GeneratedVimBindingCase(line: 151, mode: .normal, key: "' l", commandID: "vim.mark.jumpLine.l"),
	GeneratedVimBindingCase(line: 152, mode: .normal, key: "' m", commandID: "vim.mark.jumpLine.m"),
	GeneratedVimBindingCase(line: 153, mode: .normal, key: "' n", commandID: "vim.mark.jumpLine.n"),
	GeneratedVimBindingCase(line: 154, mode: .normal, key: "' o", commandID: "vim.mark.jumpLine.o"),
	GeneratedVimBindingCase(line: 155, mode: .normal, key: "' p", commandID: "vim.mark.jumpLine.p"),
	GeneratedVimBindingCase(line: 156, mode: .normal, key: "' q", commandID: "vim.mark.jumpLine.q"),
	GeneratedVimBindingCase(line: 157, mode: .normal, key: "' r", commandID: "vim.mark.jumpLine.r"),
	GeneratedVimBindingCase(line: 158, mode: .normal, key: "' s", commandID: "vim.mark.jumpLine.s"),
	GeneratedVimBindingCase(line: 159, mode: .normal, key: "' t", commandID: "vim.mark.jumpLine.t"),
	GeneratedVimBindingCase(line: 160, mode: .normal, key: "' u", commandID: "vim.mark.jumpLine.u"),
	GeneratedVimBindingCase(line: 161, mode: .normal, key: "' v", commandID: "vim.mark.jumpLine.v"),
	GeneratedVimBindingCase(line: 162, mode: .normal, key: "' w", commandID: "vim.mark.jumpLine.w"),
	GeneratedVimBindingCase(line: 163, mode: .normal, key: "' x", commandID: "vim.mark.jumpLine.x"),
	GeneratedVimBindingCase(line: 164, mode: .normal, key: "' y", commandID: "vim.mark.jumpLine.y"),
	GeneratedVimBindingCase(line: 165, mode: .normal, key: "' z", commandID: "vim.mark.jumpLine.z"),
	GeneratedVimBindingCase(line: 166, mode: .normal, key: "q a", commandID: "vim.macro.record.a"),
	GeneratedVimBindingCase(line: 167, mode: .normal, key: "q b", commandID: "vim.macro.record.b"),
	GeneratedVimBindingCase(line: 168, mode: .normal, key: "q c", commandID: "vim.macro.record.c"),
	GeneratedVimBindingCase(line: 169, mode: .normal, key: "q d", commandID: "vim.macro.record.d"),
	GeneratedVimBindingCase(line: 170, mode: .normal, key: "q e", commandID: "vim.macro.record.e"),
	GeneratedVimBindingCase(line: 171, mode: .normal, key: "q f", commandID: "vim.macro.record.f"),
	GeneratedVimBindingCase(line: 172, mode: .normal, key: "q g", commandID: "vim.macro.record.g"),
	GeneratedVimBindingCase(line: 173, mode: .normal, key: "q h", commandID: "vim.macro.record.h"),
	GeneratedVimBindingCase(line: 174, mode: .normal, key: "q i", commandID: "vim.macro.record.i"),
	GeneratedVimBindingCase(line: 175, mode: .normal, key: "q j", commandID: "vim.macro.record.j"),
	GeneratedVimBindingCase(line: 176, mode: .normal, key: "q k", commandID: "vim.macro.record.k"),
	GeneratedVimBindingCase(line: 177, mode: .normal, key: "q l", commandID: "vim.macro.record.l"),
	GeneratedVimBindingCase(line: 178, mode: .normal, key: "q m", commandID: "vim.macro.record.m"),
	GeneratedVimBindingCase(line: 179, mode: .normal, key: "q n", commandID: "vim.macro.record.n"),
	GeneratedVimBindingCase(line: 180, mode: .normal, key: "q o", commandID: "vim.macro.record.o"),
	GeneratedVimBindingCase(line: 181, mode: .normal, key: "q p", commandID: "vim.macro.record.p"),
	GeneratedVimBindingCase(line: 182, mode: .normal, key: "q q", commandID: "vim.macro.record.q"),
	GeneratedVimBindingCase(line: 183, mode: .normal, key: "q r", commandID: "vim.macro.record.r"),
	GeneratedVimBindingCase(line: 184, mode: .normal, key: "q s", commandID: "vim.macro.record.s"),
	GeneratedVimBindingCase(line: 185, mode: .normal, key: "q t", commandID: "vim.macro.record.t"),
	GeneratedVimBindingCase(line: 186, mode: .normal, key: "q u", commandID: "vim.macro.record.u"),
	GeneratedVimBindingCase(line: 187, mode: .normal, key: "q v", commandID: "vim.macro.record.v"),
	GeneratedVimBindingCase(line: 188, mode: .normal, key: "q w", commandID: "vim.macro.record.w"),
	GeneratedVimBindingCase(line: 189, mode: .normal, key: "q x", commandID: "vim.macro.record.x"),
	GeneratedVimBindingCase(line: 190, mode: .normal, key: "q y", commandID: "vim.macro.record.y"),
	GeneratedVimBindingCase(line: 191, mode: .normal, key: "q z", commandID: "vim.macro.record.z"),
	GeneratedVimBindingCase(line: 192, mode: .normal, key: "q /", commandID: "vim.searchHistory.forward"),
	GeneratedVimBindingCase(line: 193, mode: .normal, key: "q Shift-/", commandID: "vim.searchHistory.backward"),
	GeneratedVimBindingCase(line: 194, mode: .normal, key: "q Shift-;", commandID: "vim.commandHistory"),
	GeneratedVimBindingCase(line: 195, mode: .normal, key: "Shift-2", commandID: "vim.macro.replayPrefix"),
	GeneratedVimBindingCase(line: 196, mode: .normal, key: "p", commandID: "vim.pasteAfter"),
	GeneratedVimBindingCase(line: 197, mode: .normal, key: "Shift-P", commandID: "vim.pasteBefore"),
	GeneratedVimBindingCase(line: 198, mode: .normal, key: "Shift-I", commandID: "vim.insert.lineStart"),
	GeneratedVimBindingCase(line: 199, mode: .normal, key: "a", commandID: "vim.append.afterCursor"),
	GeneratedVimBindingCase(line: 200, mode: .normal, key: "Shift-A", commandID: "vim.append.lineEnd"),
	GeneratedVimBindingCase(line: 201, mode: .normal, key: "o", commandID: "vim.openLineBelow"),
	GeneratedVimBindingCase(line: 202, mode: .normal, key: "Shift-O", commandID: "vim.openLineAbove"),
	GeneratedVimBindingCase(line: 203, mode: .normal, key: "x", commandID: "vim.delete.char"),
	GeneratedVimBindingCase(line: 204, mode: .normal, key: "Shift-X", commandID: "vim.delete.charBackward"),
	GeneratedVimBindingCase(line: 205, mode: .normal, key: "Shift-D", commandID: "vim.delete.toLineEnd"),
	GeneratedVimBindingCase(line: 206, mode: .normal, key: "Shift-C", commandID: "vim.change.toLineEnd"),
	GeneratedVimBindingCase(line: 207, mode: .normal, key: "s", commandID: "vim.substitute.char"),
	GeneratedVimBindingCase(line: 208, mode: .normal, key: "Shift-S", commandID: "vim.change.line"),
	GeneratedVimBindingCase(line: 209, mode: .normal, key: "Shift-J", commandID: "vim.joinLines"),
	GeneratedVimBindingCase(line: 210, mode: .normal, key: "Shift-Y", commandID: "vim.yank.line"),
	GeneratedVimBindingCase(line: 211, mode: .normal, key: "r", commandID: "vim.replace.char"),
	GeneratedVimBindingCase(line: 212, mode: .normal, key: "Shift-R", commandID: "vim.replace.mode"),
	GeneratedVimBindingCase(line: 213, mode: .normal, key: "Shift-`", commandID: "vim.case.toggle"),
	GeneratedVimBindingCase(line: 214, mode: .normal, key: "g Shift-`", commandID: "vim.case.toggleOperator"),
	GeneratedVimBindingCase(line: 215, mode: .normal, key: "gu", commandID: "vim.case.lowerOperator"),
	GeneratedVimBindingCase(line: 216, mode: .normal, key: "g Shift-U", commandID: "vim.case.upperOperator"),
	GeneratedVimBindingCase(line: 217, mode: .normal, key: "Shift-. Shift-.", commandID: "vim.indent.right"),
	GeneratedVimBindingCase(line: 218, mode: .normal, key: "Shift-, Shift-,", commandID: "vim.indent.left"),
	GeneratedVimBindingCase(line: 219, mode: .normal, key: ".", commandID: "vim.repeatChange"),
	GeneratedVimBindingCase(line: 220, mode: .normal, key: "=", commandID: "vim.format.operator"),
	GeneratedVimBindingCase(line: 221, mode: .normal, key: "==", commandID: "vim.format.line"),
	GeneratedVimBindingCase(line: 222, mode: .normal, key: "gq", commandID: "vim.format.reflowOperator"),
	GeneratedVimBindingCase(line: 223, mode: .normal, key: "zc", commandID: "vim.fold.close"),
	GeneratedVimBindingCase(line: 224, mode: .normal, key: "zo", commandID: "vim.fold.open"),
	GeneratedVimBindingCase(line: 225, mode: .normal, key: "za", commandID: "vim.fold.toggle"),
	GeneratedVimBindingCase(line: 226, mode: .normal, key: "z Shift-C", commandID: "vim.fold.closeRecursive"),
	GeneratedVimBindingCase(line: 227, mode: .normal, key: "z Shift-O", commandID: "vim.fold.openRecursive"),
	GeneratedVimBindingCase(line: 228, mode: .normal, key: "z Shift-A", commandID: "vim.fold.toggleRecursive"),
	GeneratedVimBindingCase(line: 229, mode: .normal, key: "z Shift-M", commandID: "vim.fold.closeAll"),
	GeneratedVimBindingCase(line: 230, mode: .normal, key: "z Shift-R", commandID: "vim.fold.openAll"),
	GeneratedVimBindingCase(line: 231, mode: .normal, key: "Ctrl-W s", commandID: "pane.splitHorizontal"),
	GeneratedVimBindingCase(line: 232, mode: .normal, key: "Ctrl-W v", commandID: "pane.splitVertical"),
	GeneratedVimBindingCase(line: 233, mode: .normal, key: "Ctrl-W h", commandID: "pane.focusLeft"),
	GeneratedVimBindingCase(line: 234, mode: .normal, key: "Ctrl-W j", commandID: "pane.focusDown"),
	GeneratedVimBindingCase(line: 235, mode: .normal, key: "Ctrl-W k", commandID: "pane.focusUp"),
	GeneratedVimBindingCase(line: 236, mode: .normal, key: "Ctrl-W l", commandID: "pane.focusRight"),
	GeneratedVimBindingCase(line: 237, mode: .normal, key: "Ctrl-W w", commandID: "pane.focusNext"),
	GeneratedVimBindingCase(line: 238, mode: .normal, key: "Ctrl-W q", commandID: "pane.close"),
	GeneratedVimBindingCase(line: 239, mode: .normal, key: "Ctrl-W o", commandID: "pane.closeOthers"),
	GeneratedVimBindingCase(line: 240, mode: .normal, key: "v", commandID: "vim.visual.char"),
	GeneratedVimBindingCase(line: 241, mode: .normal, key: "Shift-V", commandID: "vim.visual.line"),
	GeneratedVimBindingCase(line: 242, mode: .normal, key: "Ctrl-V", commandID: "vim.visual.block"),
	GeneratedVimBindingCase(line: 243, mode: .normal, key: "Shift-;", commandID: "vim.ex.start"),
	GeneratedVimBindingCase(line: 244, mode: .normal, key: "u", commandID: "edit.undo"),
	GeneratedVimBindingCase(line: 245, mode: .normal, key: "Ctrl-R", commandID: "edit.redo"),
	GeneratedVimBindingCase(line: 246, mode: .normal, key: "Cmd-D", commandID: "editor.addNextSelection"),
	GeneratedVimBindingCase(line: 247, mode: .normal, key: "Cmd-Ctrl-G", commandID: "edit.selectAllFindMatches"),
	GeneratedVimBindingCase(line: 248, mode: .normal, key: "Cmd-W", commandID: "pane.close"),
	GeneratedVimBindingCase(line: 249, mode: .normal, key: "Cmd-\\", commandID: "pane.splitHorizontal"),
	GeneratedVimBindingCase(line: 250, mode: .normal, key: "Cmd-Opt-\\", commandID: "pane.splitVertical"),
	GeneratedVimBindingCase(line: 251, mode: .normal, key: "Cmd-Opt-Left", commandID: "pane.focusLeft"),
	GeneratedVimBindingCase(line: 252, mode: .normal, key: "Cmd-Opt-Right", commandID: "pane.focusRight"),
	GeneratedVimBindingCase(line: 253, mode: .normal, key: "Cmd-Opt-Up", commandID: "pane.focusUp"),
	GeneratedVimBindingCase(line: 254, mode: .normal, key: "Cmd-Opt-Down", commandID: "pane.focusDown"),
	GeneratedVimBindingCase(line: 255, mode: .normal, key: "Cmd-T", commandID: "nav.gotoSymbolWorkspace"),
	GeneratedVimBindingCase(line: 256, mode: .normal, key: "Cmd-Shift-O", commandID: "nav.gotoSymbolFile"),
	GeneratedVimBindingCase(line: 257, mode: .normal, key: "Cmd-Opt-7", commandID: "view.outline"),
	GeneratedVimBindingCase(line: 258, mode: .normal, key: "Ctrl-Alt-N", commandID: "problems.next"),
	GeneratedVimBindingCase(line: 259, mode: .normal, key: "Ctrl-Alt-P", commandID: "problems.previous"),
	GeneratedVimBindingCase(line: 260, mode: .normal, key: "Ctrl-Space", commandID: "lsp.completion"),
	GeneratedVimBindingCase(line: 261, mode: .normal, key: "Shift-K", commandID: "lsp.hover"),
	GeneratedVimBindingCase(line: 262, mode: .normal, key: "gr", commandID: "lsp.references"),
	GeneratedVimBindingCase(line: 263, mode: .normal, key: "Space f", commandID: "nav.gotoFile"),
	GeneratedVimBindingCase(line: 264, mode: .normal, key: "Space g", commandID: "nav.gotoLine"),
	GeneratedVimBindingCase(line: 265, mode: .normal, key: "Space u", commandID: "history.undoTree.toggle"),
	GeneratedVimBindingCase(line: 266, mode: .normal, key: "Space c a", commandID: "lsp.codeAction"),
	GeneratedVimBindingCase(line: 267, mode: .normal, key: "i", commandID: "mode.insert"),
	GeneratedVimBindingCase(line: 268, mode: .normal, key: "/", commandID: "vim.searchForward"),
	GeneratedVimBindingCase(line: 269, mode: .normal, key: "Shift-/", commandID: "vim.searchBackward"),
	GeneratedVimBindingCase(line: 270, mode: .normal, key: "n", commandID: "edit.findNext"),
	GeneratedVimBindingCase(line: 271, mode: .normal, key: "Shift-N", commandID: "edit.findPrevious"),
	GeneratedVimBindingCase(line: 274, mode: .visual, key: "Cmd-D", commandID: "editor.addNextSelection"),
	GeneratedVimBindingCase(line: 275, mode: .visual, key: "Cmd-Ctrl-G", commandID: "edit.selectAllFindMatches"),
	GeneratedVimBindingCase(line: 276, mode: .visual, key: "Cmd-W", commandID: "pane.close"),
	GeneratedVimBindingCase(line: 277, mode: .visual, key: "Cmd-\\", commandID: "pane.splitHorizontal"),
	GeneratedVimBindingCase(line: 278, mode: .visual, key: "Cmd-Opt-\\", commandID: "pane.splitVertical"),
	GeneratedVimBindingCase(line: 279, mode: .visual, key: "Cmd-Opt-Left", commandID: "pane.focusLeft"),
	GeneratedVimBindingCase(line: 280, mode: .visual, key: "Cmd-Opt-Right", commandID: "pane.focusRight"),
	GeneratedVimBindingCase(line: 281, mode: .visual, key: "Cmd-Opt-Up", commandID: "pane.focusUp"),
	GeneratedVimBindingCase(line: 282, mode: .visual, key: "Cmd-Opt-Down", commandID: "pane.focusDown"),
	GeneratedVimBindingCase(line: 283, mode: .visual, key: "Cmd-T", commandID: "nav.gotoSymbolWorkspace"),
	GeneratedVimBindingCase(line: 284, mode: .visual, key: "Cmd-Shift-O", commandID: "nav.gotoSymbolFile"),
	GeneratedVimBindingCase(line: 285, mode: .visual, key: "Cmd-Opt-7", commandID: "view.outline"),
	GeneratedVimBindingCase(line: 286, mode: .visual, key: "Ctrl-Alt-N", commandID: "problems.next"),
	GeneratedVimBindingCase(line: 287, mode: .visual, key: "Ctrl-Alt-P", commandID: "problems.previous"),
	GeneratedVimBindingCase(line: 288, mode: .visual, key: "Space c a", commandID: "lsp.codeAction"),
	GeneratedVimBindingCase(line: 289, mode: .visual, key: "=", commandID: "lsp.formatSelection"),
	GeneratedVimBindingCase(line: 290, mode: .visual, key: "Esc", commandID: "mode.normal"),
	GeneratedVimBindingCase(line: 291, mode: .visual, key: "h", commandID: "editor.moveLeft"),
	GeneratedVimBindingCase(line: 292, mode: .visual, key: "j", commandID: "editor.moveDown"),
	GeneratedVimBindingCase(line: 293, mode: .visual, key: "k", commandID: "editor.moveUp"),
	GeneratedVimBindingCase(line: 294, mode: .visual, key: "l", commandID: "editor.moveRight"),
	GeneratedVimBindingCase(line: 295, mode: .visual, key: "Left", commandID: "editor.moveLeft"),
	GeneratedVimBindingCase(line: 296, mode: .visual, key: "Right", commandID: "editor.moveRight"),
	GeneratedVimBindingCase(line: 297, mode: .visual, key: "Up", commandID: "editor.moveUp"),
	GeneratedVimBindingCase(line: 298, mode: .visual, key: "Down", commandID: "editor.moveDown"),
	GeneratedVimBindingCase(line: 299, mode: .visual, key: "w", commandID: "editor.moveWordForward"),
	GeneratedVimBindingCase(line: 300, mode: .visual, key: "b", commandID: "editor.moveWordBackward"),
	GeneratedVimBindingCase(line: 301, mode: .visual, key: "e", commandID: "editor.moveWordEnd"),
	GeneratedVimBindingCase(line: 302, mode: .visual, key: "0", commandID: "editor.moveLineStart"),
	GeneratedVimBindingCase(line: 303, mode: .visual, key: "Shift-4", commandID: "editor.moveLineEnd"),
	GeneratedVimBindingCase(line: 304, mode: .visual, key: "d", commandID: "vim.operator.delete"),
	GeneratedVimBindingCase(line: 305, mode: .visual, key: "c", commandID: "vim.operator.change"),
	GeneratedVimBindingCase(line: 306, mode: .visual, key: "y", commandID: "vim.operator.yank"),
	GeneratedVimBindingCase(line: 309, mode: .operatorPending, key: "h", commandID: "editor.moveLeft"),
	GeneratedVimBindingCase(line: 310, mode: .operatorPending, key: "j", commandID: "editor.moveDown"),
	GeneratedVimBindingCase(line: 311, mode: .operatorPending, key: "k", commandID: "editor.moveUp"),
	GeneratedVimBindingCase(line: 312, mode: .operatorPending, key: "l", commandID: "editor.moveRight"),
	GeneratedVimBindingCase(line: 313, mode: .operatorPending, key: "Left", commandID: "editor.moveLeft"),
	GeneratedVimBindingCase(line: 314, mode: .operatorPending, key: "Right", commandID: "editor.moveRight"),
	GeneratedVimBindingCase(line: 315, mode: .operatorPending, key: "Up", commandID: "editor.moveUp"),
	GeneratedVimBindingCase(line: 316, mode: .operatorPending, key: "Down", commandID: "editor.moveDown"),
	GeneratedVimBindingCase(line: 317, mode: .operatorPending, key: "w", commandID: "editor.moveWordForward"),
	GeneratedVimBindingCase(line: 318, mode: .operatorPending, key: "Shift-W", commandID: "editor.moveBigWordForward"),
	GeneratedVimBindingCase(line: 319, mode: .operatorPending, key: "b", commandID: "editor.moveWordBackward"),
	GeneratedVimBindingCase(line: 320, mode: .operatorPending, key: "Shift-B", commandID: "editor.moveBigWordBackward"),
	GeneratedVimBindingCase(line: 321, mode: .operatorPending, key: "e", commandID: "editor.moveWordEnd"),
	GeneratedVimBindingCase(line: 322, mode: .operatorPending, key: "Shift-E", commandID: "editor.moveBigWordEnd"),
	GeneratedVimBindingCase(line: 323, mode: .operatorPending, key: "0", commandID: "editor.moveLineStart"),
	GeneratedVimBindingCase(line: 324, mode: .operatorPending, key: "Shift-6", commandID: "editor.moveLineStart"),
	GeneratedVimBindingCase(line: 325, mode: .operatorPending, key: "Shift-4", commandID: "editor.moveLineEnd"),
	GeneratedVimBindingCase(line: 326, mode: .operatorPending, key: "d", commandID: "vim.operator.line.delete"),
	GeneratedVimBindingCase(line: 327, mode: .operatorPending, key: "c", commandID: "vim.operator.line.change"),
	GeneratedVimBindingCase(line: 328, mode: .operatorPending, key: "y", commandID: "vim.operator.line.yank"),
	GeneratedVimBindingCase(line: 329, mode: .operatorPending, key: "iw", commandID: "vim.textObject.innerWord"),
	GeneratedVimBindingCase(line: 330, mode: .operatorPending, key: "aw", commandID: "vim.textObject.aroundWord"),
	GeneratedVimBindingCase(line: 331, mode: .operatorPending, key: "is", commandID: "vim.textObject.innerSentence"),
	GeneratedVimBindingCase(line: 332, mode: .operatorPending, key: "as", commandID: "vim.textObject.aroundSentence"),
	GeneratedVimBindingCase(line: 333, mode: .operatorPending, key: "i Shift-'", commandID: "vim.textObject.innerDoubleQuote"),
	GeneratedVimBindingCase(line: 334, mode: .operatorPending, key: "a Shift-'", commandID: "vim.textObject.aroundDoubleQuote"),
	GeneratedVimBindingCase(line: 335, mode: .operatorPending, key: "i '", commandID: "vim.textObject.innerSingleQuote"),
	GeneratedVimBindingCase(line: 336, mode: .operatorPending, key: "a '", commandID: "vim.textObject.aroundSingleQuote"),
	GeneratedVimBindingCase(line: 337, mode: .operatorPending, key: "i Shift-9", commandID: "vim.textObject.innerParen"),
	GeneratedVimBindingCase(line: 338, mode: .operatorPending, key: "a Shift-9", commandID: "vim.textObject.aroundParen"),
	GeneratedVimBindingCase(line: 339, mode: .operatorPending, key: "i [", commandID: "vim.textObject.innerBracket"),
	GeneratedVimBindingCase(line: 340, mode: .operatorPending, key: "a [", commandID: "vim.textObject.aroundBracket"),
	GeneratedVimBindingCase(line: 341, mode: .operatorPending, key: "i Shift-[", commandID: "vim.textObject.innerBrace"),
	GeneratedVimBindingCase(line: 342, mode: .operatorPending, key: "a Shift-[", commandID: "vim.textObject.aroundBrace"),
	GeneratedVimBindingCase(line: 343, mode: .operatorPending, key: "ip", commandID: "vim.textObject.innerParagraph"),
	GeneratedVimBindingCase(line: 344, mode: .operatorPending, key: "ap", commandID: "vim.textObject.aroundParagraph"),
	GeneratedVimBindingCase(line: 345, mode: .operatorPending, key: "it", commandID: "vim.textObject.innerTag"),
	GeneratedVimBindingCase(line: 346, mode: .operatorPending, key: "at", commandID: "vim.textObject.aroundTag"),
	GeneratedVimBindingCase(line: 349, mode: .insert, key: "Left", commandID: "editor.moveLeft"),
	GeneratedVimBindingCase(line: 350, mode: .insert, key: "Right", commandID: "editor.moveRight"),
	GeneratedVimBindingCase(line: 351, mode: .insert, key: "Up", commandID: "editor.moveUp"),
	GeneratedVimBindingCase(line: 352, mode: .insert, key: "Down", commandID: "editor.moveDown"),
	GeneratedVimBindingCase(line: 353, mode: .insert, key: "Shift-Left", commandID: "editor.extendLeft"),
	GeneratedVimBindingCase(line: 354, mode: .insert, key: "Shift-Right", commandID: "editor.extendRight"),
	GeneratedVimBindingCase(line: 355, mode: .insert, key: "Shift-Up", commandID: "editor.extendUp"),
	GeneratedVimBindingCase(line: 356, mode: .insert, key: "Shift-Down", commandID: "editor.extendDown"),
	GeneratedVimBindingCase(line: 357, mode: .insert, key: "Cmd-D", commandID: "editor.addNextSelection"),
	GeneratedVimBindingCase(line: 358, mode: .insert, key: "Cmd-Ctrl-G", commandID: "edit.selectAllFindMatches"),
	GeneratedVimBindingCase(line: 359, mode: .insert, key: "Cmd-W", commandID: "pane.close"),
	GeneratedVimBindingCase(line: 360, mode: .insert, key: "Cmd-\\", commandID: "pane.splitHorizontal"),
	GeneratedVimBindingCase(line: 361, mode: .insert, key: "Cmd-Opt-\\", commandID: "pane.splitVertical"),
	GeneratedVimBindingCase(line: 362, mode: .insert, key: "Cmd-Opt-Left", commandID: "pane.focusLeft"),
	GeneratedVimBindingCase(line: 363, mode: .insert, key: "Cmd-Opt-Right", commandID: "pane.focusRight"),
	GeneratedVimBindingCase(line: 364, mode: .insert, key: "Cmd-Opt-Up", commandID: "pane.focusUp"),
	GeneratedVimBindingCase(line: 365, mode: .insert, key: "Cmd-Opt-Down", commandID: "pane.focusDown"),
	GeneratedVimBindingCase(line: 366, mode: .insert, key: "Cmd-T", commandID: "nav.gotoSymbolWorkspace"),
	GeneratedVimBindingCase(line: 367, mode: .insert, key: "Cmd-Shift-O", commandID: "nav.gotoSymbolFile"),
	GeneratedVimBindingCase(line: 368, mode: .insert, key: "Cmd-Opt-7", commandID: "view.outline"),
	GeneratedVimBindingCase(line: 369, mode: .insert, key: "Ctrl-Alt-N", commandID: "problems.next"),
	GeneratedVimBindingCase(line: 370, mode: .insert, key: "Ctrl-Alt-P", commandID: "problems.previous"),
	GeneratedVimBindingCase(line: 371, mode: .insert, key: "Esc", commandID: "mode.normal"),
	GeneratedVimBindingCase(line: 372, mode: .insert, key: "Ctrl-Space", commandID: "lsp.completion"),
	GeneratedVimBindingCase(line: 373, mode: .insert, key: "jk", commandID: "mode.normal"),
]
private let generatedVimBindingCaseCount = 364

struct GeneratedVimBindingCase: CustomTestStringConvertible {
	let line: Int
	let mode: ItsyKeymap.Mode
	let key: String
	let commandID: String

	var testDescription: String {
		"line \(line) \(mode) \(key) -> \(commandID)"
	}

	func binding() throws -> ItsyKeymap.KeyBinding {
		try ItsyKeymap.KeymapLoader.binding(mode: mode, key: key, commandID: commandID)
	}
}

@Test func generatedVimBindingCasesMatchBundledProfile() throws {
	let actual = try bundledVimBindings().map(bindingSignature(_:))
	let expected = try generatedVimBindingCases.map { try bindingSignature($0.binding()) }
	#expect(actual == expected)
	#expect(expected.count == generatedVimBindingCaseCount)
}

@Test(arguments: generatedVimBindingCases)
func generatedVimBindingResolvesBundledKeymap(_ testCase: GeneratedVimBindingCase) throws {
	let bindings = try bundledVimBindings()
	let binding = try testCase.binding()
	#expect(bindings.contains(binding))
	var engine = ItsyKeymap.KeymapEngine(modeStack: [binding.mode], bindings: bindings)
	var result = ItsyKeymap.KeymapResult.passthrough
	for key in binding.chord {
		result = engine.handle(try keyEvent(for: key))
	}
	if hasLongerBindingPrefix(binding, in: bindings) {
		#expect(result == .partial)
		#expect(engine.pendingChord == binding.chord)
	} else {
		#expect(result == .command(binding.commandID))
		#expect(engine.pendingChord.isEmpty)
	}
}

@Test(arguments: generatedVimBindingCases)
func generatedVimBindingCommandRouteIsStable(_ testCase: GeneratedVimBindingCase) {
	var engine = ItsyVim.VimEngine(
		mode: vimMode(for: testCase.mode),
		pendingOperator: testCase.mode == .operatorPending ? .delete : nil
	)
	if testCase.mode == .visual {
		engine.visualMode = .character
	}
	let action = engine.handle(commandID: testCase.commandID, count: 1, hasSelection: testCase.mode == .visual)
	#expect(action == expectedCommandAction(for: testCase.commandID, mode: testCase.mode))
}

private func bundledVimBindings() throws -> [ItsyKeymap.KeyBinding] {
	try ItsyKeymap.KeymapConfiguration.load(profile: .vim, userConfigURL: nil)
}

private func bindingSignature(_ binding: ItsyKeymap.KeyBinding) -> String {
	let chord = binding.chord.map(keySignature(_:)).joined(separator: " ")
	return "\(binding.mode)|\(chord)|\(binding.commandID)"
}

private func keySignature(_ key: ItsyKeymap.Key) -> String {
	let modifiers: [(ItsyKeymap.KeyModifiers, String)] = [
		(.command, "cmd"),
		(.control, "ctrl"),
		(.option, "opt"),
		(.shift, "shift"),
	]
	let prefix = modifiers.compactMap { key.modifiers.contains($0.0) ? $0.1 : nil }.joined(separator: "+")
	return prefix.isEmpty ? key.value : "\(prefix)+\(key.value)"
}

private func hasLongerBindingPrefix(_ binding: ItsyKeymap.KeyBinding, in bindings: [ItsyKeymap.KeyBinding]) -> Bool {
	bindings.contains {
		$0.mode == binding.mode &&
			$0.chord.count > binding.chord.count &&
			Array($0.chord.prefix(binding.chord.count)) == binding.chord
	}
}

private func keyEvent(for key: ItsyKeymap.Key) throws -> NSEvent {
	let keyInfo = eventKeyInfo(for: key.value)
	return try #require(NSEvent.keyEvent(
		with: .keyDown,
		location: .zero,
		modifierFlags: eventModifiers(for: key.modifiers),
		timestamp: 0,
		windowNumber: 0,
		context: nil,
		characters: keyInfo.characters,
		charactersIgnoringModifiers: keyInfo.charactersIgnoringModifiers,
		isARepeat: false,
		keyCode: keyInfo.keyCode
	))
}

private func eventKeyInfo(for value: String) -> (characters: String, charactersIgnoringModifiers: String, keyCode: UInt16) {
	switch value {
	case "escape":
		return ("\u{1B}", "\u{1B}", 53)
	case "space":
		return (" ", " ", 49)
	case "left":
		return ("", "", 123)
	case "right":
		return ("", "", 124)
	case "down":
		return ("", "", 125)
	case "up":
		return ("", "", 126)
	case "return":
		return ("\r", "\r", 36)
	case "tab":
		return ("\t", "\t", 48)
	case "delete":
		return ("\u{7F}", "\u{7F}", 51)
	default:
		return (value, value.lowercased(), 0)
	}
}

private func eventModifiers(for modifiers: ItsyKeymap.KeyModifiers) -> NSEvent.ModifierFlags {
	var flags: NSEvent.ModifierFlags = []
	if modifiers.contains(.command) {
		flags.insert(.command)
	}
	if modifiers.contains(.shift) {
		flags.insert(.shift)
	}
	if modifiers.contains(.option) {
		flags.insert(.option)
	}
	if modifiers.contains(.control) {
		flags.insert(.control)
	}
	return flags
}

private func vimMode(for mode: ItsyKeymap.Mode) -> ItsyVim.Mode {
	switch mode {
	case .global:
		return .normal
	case .normal:
		return .normal
	case .insert:
		return .insert
	case .visual:
		return .visual(.character)
	case .operatorPending:
		return .operatorPending
	case .command, .emacs:
		return .normal
	}
}

private func expectedCommandAction(for commandID: String, mode: ItsyKeymap.Mode) -> ItsyVim.VimCommandAction? {
	if let mark = suffix(commandID, after: "vim.mark.set."), mark.count == 1, let character = mark.first {
		return .setMark(character)
	}
	if let mark = suffix(commandID, after: "vim.mark.jump.") ?? suffix(commandID, after: "vim.mark.jumpLine."), mark.count == 1, let character = mark.first {
		return .jumpToMark(character)
	}
	if let register = suffix(commandID, after: "vim.macro.record.") {
		return .macroRecord(register)
	}
	if motionCommandIDs.contains(commandID) {
		if mode == .visual {
			return .visualMotion(commandID)
		}
		if mode == .operatorPending {
			return .applyPendingOperatorMotion(commandID)
		}
		return .motion(commandID)
	}
	if textObjectCommandIDs.contains(commandID), mode == .operatorPending {
		return .applyPendingOperatorTextObject(commandID)
	}
	switch commandID {
	case "editor.findCharForward":
		return .beginCharacterMotion(.findForward)
	case "editor.findCharBackward":
		return .beginCharacterMotion(.findBackward)
	case "editor.tillCharForward":
		return .beginCharacterMotion(.tillForward)
	case "editor.tillCharBackward":
		return .beginCharacterMotion(.tillBackward)
	case "editor.repeatCharFind":
		return .repeatCharacterMotion(reversed: false)
	case "editor.repeatCharFindReverse":
		return .repeatCharacterMotion(reversed: true)
	case "edit.undo":
		return .undo
	case "edit.redo":
		return .redo
	case "editor.addNextSelection":
		return .addNextSelection
	case "vim.operator.delete":
		return mode == .visual ? .applySelectionOperator(.delete) : .beginOperator(.delete)
	case "vim.operator.change":
		return mode == .visual ? .applySelectionOperator(.change) : .beginOperator(.change)
	case "vim.operator.yank":
		return mode == .visual ? .applySelectionOperator(.yank) : .beginOperator(.yank)
	case "vim.case.toggle":
		return .toggleCaseAtCursor
	case "vim.case.toggleOperator":
		return mode == .visual ? .applySelectionOperator(.toggleCase) : .beginOperator(.toggleCase)
	case "vim.case.lowerOperator":
		return mode == .visual ? .applySelectionOperator(.lowercase) : .beginOperator(.lowercase)
	case "vim.case.upperOperator":
		return mode == .visual ? .applySelectionOperator(.uppercase) : .beginOperator(.uppercase)
	case "vim.indent.right":
		return mode == .visual ? .applySelectionOperator(.indentRight) : .lineOperator(.indentRight)
	case "vim.indent.left":
		return mode == .visual ? .applySelectionOperator(.indentLeft) : .lineOperator(.indentLeft)
	case "vim.repeatChange":
		return .repeatLastChange
	case "vim.registerPrefix":
		return .handled
	case "vim.jumpBack":
		return .jumpBack
	case "vim.macro.recordPrefix":
		return .macroRecordPrefix
	case "vim.macro.replayPrefix":
		return .macroReplayPrefix
	case "vim.pasteAfter":
		return .paste(after: true)
	case "vim.pasteBefore":
		return .paste(after: false)
	case "vim.insert.lineStart":
		return .insertLineStart
	case "vim.append.afterCursor":
		return .appendAfterCursor
	case "vim.append.lineEnd":
		return .appendLineEnd
	case "vim.openLineBelow":
		return .openLine(after: true)
	case "vim.openLineAbove":
		return .openLine(after: false)
	case "vim.delete.char":
		return .deleteCharacter(backward: false, count: 1)
	case "vim.delete.charBackward":
		return .deleteCharacter(backward: true, count: 1)
	case "vim.delete.toLineEnd":
		return .deleteToLineEnd(change: false)
	case "vim.change.toLineEnd":
		return .deleteToLineEnd(change: true)
	case "vim.substitute.char":
		return .substituteCharacter(count: 1)
	case "vim.change.line":
		return .lineOperator(.change)
	case "vim.joinLines":
		return .joinLines
	case "vim.yank.line":
		return .lineOperator(.yank)
	case "vim.replace.char":
		return .replaceCharacter
	case "vim.replace.mode":
		return .replaceMode
	case "vim.ex.start":
		return .exStart
	case "vim.visual.char":
		return .beginVisualMode(.character)
	case "vim.visual.line":
		return .beginVisualMode(.line)
	case "vim.visual.block":
		return .beginVisualMode(.block)
	case "vim.operator.line.delete":
		return .lineOperator(.delete)
	case "vim.operator.line.change":
		return .lineOperator(.change)
	case "vim.operator.line.yank":
		return .lineOperator(.yank)
	case "vim.format.operator", "vim.format.line", "vim.format.reflowOperator",
	     "vim.fold.close", "vim.fold.open", "vim.fold.toggle", "vim.fold.closeRecursive", "vim.fold.openRecursive",
	     "vim.fold.toggleRecursive", "vim.fold.closeAll", "vim.fold.openAll":
		return .hostCommand(commandID)
	case "vim.searchHistory.forward":
		return .search("edit.findNext", recordsJump: false)
	case "vim.searchHistory.backward":
		return .search("edit.findPrevious", recordsJump: false)
	case "vim.commandHistory":
		return .hostCommand("view.commandPalette")
	case "edit.findNext", "edit.findPrevious", "vim.searchForward", "vim.searchBackward":
		return .search(commandID, recordsJump: mode == .normal || mode == .global)
	case "file.save":
		return .save
	case "file.close":
		return .close
	case "mode.normal":
		return .normalMode
	case "mode.insert":
		return .insertMode
	case "mode.emacs":
		return .emacsMode
	case "vim.textObject.innerSentence", "vim.textObject.aroundSentence":
		return .normalMode
	default:
		return nil
	}
}

private func suffix(_ value: String, after prefix: String) -> String? {
	guard value.hasPrefix(prefix) else {
		return nil
	}
	let suffix = String(value.dropFirst(prefix.count))
	return suffix.isEmpty ? nil : suffix
}

private let motionCommandIDs: Set<String> = [
	"editor.moveLeft",
	"editor.moveRight",
	"editor.moveDown",
	"editor.moveUp",
	"editor.moveWordForward",
	"editor.moveWordBackward",
	"editor.moveWordEnd",
	"editor.moveBigWordForward",
	"editor.moveBigWordBackward",
	"editor.moveBigWordEnd",
	"editor.moveLineStart",
	"editor.moveLineEnd",
	"editor.moveBufferStart",
	"editor.moveBufferEnd",
	"editor.moveParagraphForward",
	"editor.moveParagraphBackward",
]

private let textObjectCommandIDs: Set<String> = [
	"vim.textObject.innerWord",
	"vim.textObject.aroundWord",
	"vim.textObject.innerDoubleQuote",
	"vim.textObject.aroundDoubleQuote",
	"vim.textObject.innerSingleQuote",
	"vim.textObject.aroundSingleQuote",
	"vim.textObject.innerParen",
	"vim.textObject.aroundParen",
	"vim.textObject.innerBracket",
	"vim.textObject.aroundBracket",
	"vim.textObject.innerBrace",
	"vim.textObject.aroundBrace",
	"vim.textObject.innerParagraph",
	"vim.textObject.aroundParagraph",
	"vim.textObject.innerTag",
	"vim.textObject.aroundTag",
]
