// swift-tools-version:5.9

import PackageDescription

let releaseSwiftSettings: [SwiftSetting] = [
	.unsafeFlags([
		"-Xfrontend", "-disable-reflection-metadata",
		"-Xfrontend", "-disable-concrete-type-metadata-mangled-name-accessors",
	], .when(configuration: .release)),
]

let package = Package(
	name: "Itsy",
	platforms: [
		.macOS(.v13),
	],
	products: [
		.executable(name: "ItsyApp", targets: ["ItsyApp"]),
		.executable(name: "itsy", targets: ["ItsyConfigCLI"]),
		.executable(name: "ItsyBench", targets: ["ItsyBench"]),
		.library(name: "ItsyConfig", type: .static, targets: ["ItsyConfig"]),
		.library(name: "ItsyWorkbenchLayout", type: .static, targets: ["ItsyWorkbenchLayout"]),
		.library(name: "ItsyWorkbenchDSL", type: .static, targets: ["ItsyWorkbenchDSL"]),
		.library(name: "ItsyRender", type: .static, targets: ["ItsyRender"]),
		.library(name: "ItsyEditor", type: .static, targets: ["ItsyEditor"]),
		.library(name: "ItsySyntax", type: .static, targets: ["ItsySyntax"]),
		.library(name: "ItsyKeymap", type: .static, targets: ["ItsyKeymap"]),
		.library(name: "ItsyVim", type: .static, targets: ["ItsyVim"]),
		.library(name: "ItsyLSP", type: .static, targets: ["ItsyLSP"]),
		.library(name: "ItsyDAP", type: .static, targets: ["ItsyDAP"]),
		.library(name: "ItsyDebugger", type: .static, targets: ["ItsyDebugger"]),
		.library(name: "CLua", type: .static, targets: ["CLua"]),
		.library(name: "CLibgit2", type: .static, targets: ["CLibgit2"]),
		.library(name: "CTreeSitter", type: .static, targets: ["CTreeSitter"]),
		.library(name: "CTSGrammars", type: .static, targets: ["CTSGrammars"]),
	],
	dependencies: [
		.package(url: "https://github.com/sparkle-project/Sparkle", from: "2.9.4"),
	],
	targets: [
		.executableTarget(
			name: "ItsyApp",
			dependencies: [
				"ItsyConfig", "ItsyWorkbenchLayout", "ItsyWorkbenchDSL", "ItsyRender", "ItsyEditor", "ItsySyntax", "ItsyKeymap", "ItsyLSP", "ItsyDAP", "ItsyDebugger",
				.product(name: "Sparkle", package: "Sparkle"),
			],
			exclude: ["README.md"],
			swiftSettings: releaseSwiftSettings,
			linkerSettings: [
				.unsafeFlags(["-Xlinker", "-rpath", "-Xlinker", "@executable_path/../Frameworks"]),
			]
		),
		.executableTarget(name: "ItsyConfigCLI", dependencies: ["ItsyConfig"], swiftSettings: releaseSwiftSettings),
		.target(name: "ItsyConfig", dependencies: ["ItsyWorkbenchDSL"], swiftSettings: releaseSwiftSettings),
		.target(name: "ItsyWorkbenchLayout", swiftSettings: releaseSwiftSettings),
		.target(name: "ItsyWorkbenchDSL", dependencies: ["ItsyWorkbenchLayout"], swiftSettings: releaseSwiftSettings),
		.target(name: "ItsyRender", dependencies: ["ItsyEditor", "ItsyKeymap", "ItsyVim"], resources: [.copy("Shaders.metal")], swiftSettings: releaseSwiftSettings),
		.target(name: "ItsyEditor", dependencies: ["CLibgit2", "ItsyConfig", "ItsyLSP"], swiftSettings: releaseSwiftSettings),
		.target(name: "ItsySyntax", dependencies: ["CTreeSitter", "ItsyEditor"], resources: [.copy("Resources")], swiftSettings: releaseSwiftSettings),
		.target(name: "ItsyKeymap", resources: [.process("Resources")], swiftSettings: releaseSwiftSettings),
		.target(name: "ItsyVim", swiftSettings: releaseSwiftSettings),
		.target(name: "ItsyLSP", swiftSettings: releaseSwiftSettings),
		.target(name: "ItsyDAP", swiftSettings: releaseSwiftSettings),
		.target(name: "ItsyDebugger", dependencies: ["ItsyDAP", "ItsyEditor"], swiftSettings: releaseSwiftSettings),
		.executableTarget(name: "ItsyBench", dependencies: ["ItsyEditor", "ItsyRender", "ItsySyntax"], swiftSettings: releaseSwiftSettings),
		.target(
			name: "CLua",
			path: "Sources/CLua",
			sources: [
				"upstream/src/lapi.c",
				"upstream/src/lauxlib.c",
				"upstream/src/lbaselib.c",
				"upstream/src/lcode.c",
				"upstream/src/lcorolib.c",
				"upstream/src/lctype.c",
				"upstream/src/ldblib.c",
				"upstream/src/ldebug.c",
				"upstream/src/ldo.c",
				"upstream/src/ldump.c",
				"upstream/src/lfunc.c",
				"upstream/src/lgc.c",
				"upstream/src/linit.c",
				"upstream/src/liolib.c",
				"upstream/src/llex.c",
				"upstream/src/lmathlib.c",
				"upstream/src/lmem.c",
				"upstream/src/loadlib.c",
				"upstream/src/lobject.c",
				"upstream/src/lopcodes.c",
				"upstream/src/loslib.c",
				"upstream/src/lparser.c",
				"upstream/src/lstate.c",
				"upstream/src/lstring.c",
				"upstream/src/lstrlib.c",
				"upstream/src/ltable.c",
				"upstream/src/ltablib.c",
				"upstream/src/ltm.c",
				"upstream/src/lundump.c",
				"upstream/src/lutf8lib.c",
				"upstream/src/lvm.c",
				"upstream/src/lzio.c",
			],
			publicHeadersPath: ".",
			cSettings: [
				.headerSearchPath("upstream/src"),
				.define("LUA_USE_MACOSX"),
				.unsafeFlags(["-O3"], .when(configuration: .release)),
			]
		),
		.target(
			name: "CLibgit2",
			path: "Sources/CLibgit2",
			exclude: [
				"upstream/deps/llhttp/CMakeLists.txt",
				"upstream/deps/llhttp/LICENSE-MIT",
				"upstream/deps/pcre/CMakeLists.txt",
				"upstream/deps/pcre/COPYING",
				"upstream/deps/pcre/LICENCE",
				"upstream/deps/pcre/cmake",
				"upstream/deps/pcre/config.h.in",
				"upstream/deps/xdiff/CMakeLists.txt",
				"upstream/deps/zlib/CMakeLists.txt",
				"upstream/deps/zlib/LICENSE",
				"upstream/src/libgit2/CMakeLists.txt",
				"upstream/src/libgit2/config.cmake.in",
				"upstream/src/libgit2/experimental.h.in",
				"upstream/src/libgit2/git2.rc",
			],
			sources: [
				"upstream/src/libgit2",
				"upstream/deps/llhttp",
				"upstream/deps/pcre",
				"upstream/deps/xdiff",
				"upstream/deps/zlib",
				"upstream/src/util/alloc.c",
				"upstream/src/util/allocators/debugalloc.c",
				"upstream/src/util/allocators/failalloc.c",
				"upstream/src/util/allocators/stdalloc.c",
				"upstream/src/util/date.c",
				"upstream/src/util/errors.c",
				"upstream/src/util/filebuf.c",
				"upstream/src/util/fs_path.c",
				"upstream/src/util/futils.c",
				"upstream/src/util/hash.c",
				"upstream/src/util/hash/common_crypto.c",
				"upstream/src/util/net.c",
				"upstream/src/util/pool.c",
				"upstream/src/util/posix.c",
				"upstream/src/util/pqueue.c",
				"upstream/src/util/rand.c",
				"upstream/src/util/regexp.c",
				"upstream/src/util/runtime.c",
				"upstream/src/util/sortedcache.c",
				"upstream/src/util/str.c",
				"upstream/src/util/strlist.c",
				"upstream/src/util/thread.c",
				"upstream/src/util/tsort.c",
				"upstream/src/util/unix/map.c",
				"upstream/src/util/unix/process.c",
				"upstream/src/util/unix/realpath.c",
				"upstream/src/util/utf8.c",
				"upstream/src/util/util.c",
				"upstream/src/util/varint.c",
				"upstream/src/util/vector.c",
				"upstream/src/util/wildmatch.c",
				"upstream/src/util/zstream.c",
			],
			publicHeadersPath: ".",
			cSettings: [
				.headerSearchPath("gen_headers"),
				.headerSearchPath("gen_headers/pcre"),
				.headerSearchPath("upstream/include"),
				.headerSearchPath("upstream/src/libgit2"),
				.headerSearchPath("upstream/src/util"),
				.headerSearchPath("upstream/deps/llhttp"),
				.headerSearchPath("upstream/deps/pcre"),
				.headerSearchPath("upstream/deps/xdiff"),
				.headerSearchPath("upstream/deps/zlib"),
				.define("NO_VIZ"),
				.define("STDC"),
				.define("NO_GZIP"),
				.define("HAVE_SYS_TYPES_H"),
				.define("HAVE_STDINT_H"),
				.define("HAVE_STDDEF_H"),
				.define("HAVE_CONFIG_H"),
				.unsafeFlags(["-DUSE_HTTPS=SecureTransport", "-DUSE_SHA1=CommonCrypto"]),
				.unsafeFlags(["-fno-modules"]),
				.unsafeFlags(["-Wno-deprecated-declarations"]),
				.unsafeFlags(["-O3"], .when(configuration: .release)),
			],
			linkerSettings: [
				.linkedFramework("CoreFoundation"),
				.linkedFramework("Security"),
				.linkedLibrary("iconv"),
			]
		),
		.target(
			name: "CTreeSitter",
			path: "Sources/CTreeSitter",
			sources: ["upstream/lib/src/lib.c"],
			publicHeadersPath: "upstream/lib/include",
			cSettings: [
				.headerSearchPath("upstream/lib/src"),
				.unsafeFlags(["-O3"], .when(configuration: .release)),
			]
		),
		.target(
			name: "CTSGrammars",
			path: "Sources/CTSGrammars",
			sources: [
				"grammars/bash/src/parser.c",
				"grammars/bash/src/scanner.c",
				"grammars/c/src/parser.c",
				"grammars/c-sharp/src/parser.c",
				"grammars/c-sharp/src/scanner.c",
				"grammars/cpp/src/parser.c",
				"grammars/cpp/src/scanner.c",
				"grammars/css/src/parser.c",
				"grammars/css/src/scanner.c",
				"grammars/dart/src/parser.c",
				"grammars/dart/src/scanner.c",
				"grammars/dockerfile/src/parser.c",
				"grammars/dockerfile/src/scanner.c",
				"grammars/elixir/src/parser.c",
				"grammars/elixir/src/scanner.c",
				"grammars/go/src/parser.c",
				"generated/graphql/parser.c",
				"grammars/haskell/src/parser.c",
				"grammars/haskell/src/scanner.c",
				"grammars/hcl/dialects/terraform/src/parser.c",
				"grammars/hcl/dialects/terraform/src/scanner.c",
				"grammars/html/src/parser.c",
				"grammars/html/src/scanner.c",
				"grammars/java/src/parser.c",
				"grammars/javascript/src/parser.c",
				"grammars/javascript/src/scanner.c",
				"grammars/julia/src/parser.c",
				"grammars/julia/src/scanner.c",
				"grammars/json/src/parser.c",
				"grammars/kotlin/src/parser.c",
				"grammars/kotlin/src/scanner.c",
				"generated/latex/parser.c",
				"grammars/latex/src/scanner.c",
				"grammars/lua/src/parser.c",
				"grammars/lua/src/scanner.c",
				"grammars/markdown/tree-sitter-markdown/src/parser.c",
				"grammars/markdown/tree-sitter-markdown/src/scanner.c",
				"grammars/markdown/tree-sitter-markdown-inline/src/parser.c",
				"grammars/markdown/tree-sitter-markdown-inline/src/scanner.c",
				"grammars/nix/src/parser.c",
				"grammars/nix/src/scanner.c",
				"grammars/ocaml/grammars/ocaml/src/parser.c",
				"grammars/ocaml/grammars/ocaml/src/scanner.c",
				"grammars/php/php/src/parser.c",
				"grammars/php/php/src/scanner.c",
				"generated/proto/parser.c",
				"grammars/python/src/parser.c",
				"grammars/python/src/scanner.c",
				"grammars/r/src/parser.c",
				"grammars/r/src/scanner.c",
				"grammars/ruby/src/parser.c",
				"grammars/ruby/src/scanner.c",
				"grammars/rust/src/parser.c",
				"grammars/rust/src/scanner.c",
				"generated/scss/parser.c",
				"grammars/scss/src/scanner.c",
				"grammars/sql/src/parser.c",
				"grammars/sql/src/scanner.c",
				"grammars/svelte/src/parser.c",
				"grammars/svelte/src/scanner.c",
				"grammars/swift/src/parser.c",
				"grammars/swift/src/scanner.c",
				"grammars/toml/src/parser.c",
				"grammars/toml/src/scanner.c",
				"grammars/typescript/typescript/src/parser.c",
				"grammars/typescript/typescript/src/scanner.c",
				"grammars/typescript/tsx/src/parser.c",
				"grammars/typescript/tsx/src/scanner.c",
				"generated/vue/parser.c",
				"generated/vue/scanner.cc",
				"grammars/yaml/src/parser.c",
				"grammars/yaml/src/scanner.c",
				"grammars/zig/src/parser.c",
			],
			publicHeadersPath: "include",
			cSettings: [
				.headerSearchPath("grammars/bash/src"),
				.headerSearchPath("grammars/c/src"),
				.headerSearchPath("grammars/c-sharp/src"),
				.headerSearchPath("grammars/cpp/src"),
				.headerSearchPath("grammars/css/src"),
				.headerSearchPath("grammars/dart/src"),
				.headerSearchPath("grammars/dockerfile/src"),
				.headerSearchPath("grammars/elixir/src"),
				.headerSearchPath("grammars/go/src"),
				.headerSearchPath("grammars/graphql/src"),
				.headerSearchPath("grammars/haskell/src"),
				.headerSearchPath("grammars/hcl/dialects/terraform/src"),
				.headerSearchPath("grammars/html/src"),
				.headerSearchPath("grammars/java/src"),
				.headerSearchPath("grammars/javascript/src"),
				.headerSearchPath("grammars/julia/src"),
				.headerSearchPath("grammars/json/src"),
				.headerSearchPath("grammars/kotlin/src"),
				.headerSearchPath("generated/latex"),
				.headerSearchPath("grammars/lua/src"),
				.headerSearchPath("grammars/markdown/tree-sitter-markdown/src"),
				.headerSearchPath("grammars/markdown/tree-sitter-markdown-inline/src"),
				.headerSearchPath("grammars/nix/src"),
				.headerSearchPath("grammars/ocaml/grammars/ocaml/src"),
				.headerSearchPath("grammars/php/php/src"),
				.headerSearchPath("grammars/proto/src"),
				.headerSearchPath("grammars/python/src"),
				.headerSearchPath("grammars/r/src"),
				.headerSearchPath("grammars/ruby/src"),
				.headerSearchPath("grammars/rust/src"),
				.headerSearchPath("grammars/scss/src"),
				.headerSearchPath("grammars/sql/src"),
				.headerSearchPath("grammars/svelte/src"),
				.headerSearchPath("grammars/swift/src"),
				.headerSearchPath("grammars/toml/src"),
				.headerSearchPath("grammars/typescript/typescript/src"),
				.headerSearchPath("grammars/typescript/tsx/src"),
				.headerSearchPath("grammars/vue/src"),
				.headerSearchPath("grammars/yaml/src"),
				.headerSearchPath("grammars/zig/src"),
				.unsafeFlags(["-O3"], .when(configuration: .release)),
			]
		),
		.testTarget(name: "ItsyEditorTests", dependencies: ["ItsyEditor", "ItsyConfig", "ItsyLSP"], resources: [.copy("Fixtures")]),
		.testTarget(name: "ItsyConfigTests", dependencies: ["ItsyConfig"]),
		.testTarget(name: "ItsyWorkbenchLayoutTests", dependencies: ["ItsyWorkbenchLayout", "ItsyWorkbenchDSL"]),
		.testTarget(name: "ItsyKeymapTests", dependencies: ["ItsyKeymap"]),
		.testTarget(name: "ItsyVimTests", dependencies: ["ItsyVim", "ItsyKeymap"]),
		.testTarget(name: "ItsyRenderTests", dependencies: ["ItsyRender"]),
		.testTarget(name: "ItsyAppTests", dependencies: ["ItsyApp", "ItsyEditor"], resources: [.copy("Fixtures")]),
		.testTarget(name: "ItsyUISnapshotTests", dependencies: ["ItsyApp", "ItsyRender", "ItsyEditor", "ItsyConfig"], resources: [.copy("Fixtures")]),
		.testTarget(name: "ItsySyntaxTests", dependencies: ["ItsySyntax", "ItsyEditor", "CTSGrammars"]),
		.testTarget(name: "ItsyLSPTests", dependencies: ["ItsyLSP"]),
		.testTarget(name: "ItsyDAPTests", dependencies: ["ItsyDAP"]),
		.testTarget(name: "ItsyDebuggerTests", dependencies: ["ItsyDebugger", "ItsyDAP"]),
		.testTarget(name: "ItsyIntegrationTests", dependencies: ["ItsyApp", "ItsyEditor", "ItsyLSP", "ItsyDAP", "ItsyDebugger"]),
		.testTarget(name: "CLuaTests", dependencies: ["CLua"]),
		.testTarget(name: "CLibgit2Tests", dependencies: ["CLibgit2"]),
		.testTarget(name: "CTSGrammarsTests", dependencies: ["CTSGrammars", "CTreeSitter"]),
	]
)
