package shed;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class JobQuickfixControllerTest {
    @TempDir
    Path temporaryDirectory;

    @Test
    void ctestFallbackUsesDirectArgumentsForTheOnlyGeneratedTree() throws Exception {
        Path workspace = Files.createDirectories(temporaryDirectory.resolve("workspace with spaces"));
        Path build = Files.createDirectories(workspace.resolve("build"));
        Files.writeString(build.resolve("CTestTestfile.cmake"), "# generated by CMake\n");

        TaskService.WorkspaceTask task = new JobQuickfixController(null).inferBuiltInTask("test", workspace.toFile());

        assertEquals(List.of("ctest", "--test-dir", build.toAbsolutePath().normalize().toString(), "--output-on-failure"), task.directArguments());
        assertFalse(task.hasShellArguments());
        assertEquals(TaskService.ShellPolicy.DIRECT, task.shell());
    }

    @Test
    void ctestFallbackDeclinesAmbiguousGeneratedTrees() throws Exception {
        for (String name : List.of("build", "cmake-build-debug")) {
            Path directory = Files.createDirectories(temporaryDirectory.resolve(name));
            Files.writeString(directory.resolve("CTestTestfile.cmake"), "# generated by CMake\n");
            Files.writeString(directory.resolve("CMakeCache.txt"), "# generated by CMake\n");
        }

        assertNull(new JobQuickfixController(null).inferBuiltInTask("test", temporaryDirectory.toFile()));
        assertNull(new JobQuickfixController(null).inferBuiltInTask("build", temporaryDirectory.toFile()));
    }

    @Test
    void cmakeBuildFallbackUsesDirectArgumentsForTheOnlyGeneratedTree() throws Exception {
        Path workspace = Files.createDirectories(temporaryDirectory.resolve("workspace with spaces"));
        Path build = Files.createDirectories(workspace.resolve("build"));
        Files.writeString(build.resolve("CMakeCache.txt"), "# generated by CMake\n");

        TaskService.WorkspaceTask task = new JobQuickfixController(null).inferBuiltInTask("build", workspace.toFile());

        assertEquals(List.of("cmake", "--build", build.toAbsolutePath().normalize().toString()), task.directArguments());
        assertFalse(task.hasShellArguments());
        assertEquals(TaskService.ShellPolicy.DIRECT, task.shell());
    }

    @Test
    void buildsOnlyDirectArgumentsForExplicitCmakePresets() throws Exception {
        assertEquals(List.of("cmake", "--preset", "debug local"), JobQuickfixController.cmakePresetArguments("configure", "debug local"));
        assertEquals(List.of("cmake", "--build", "--preset", "debug"), JobQuickfixController.cmakePresetArguments("build", "debug"));
        assertEquals(List.of("ctest", "--preset", "debug"), JobQuickfixController.cmakePresetArguments("test", "debug"));
        assertEquals(List.of("cpack", "--preset", "release package"), JobQuickfixController.cmakePresetArguments("package", "release package"));
        assertEquals(List.of("cmake", "--workflow", "--preset", "ci"), JobQuickfixController.cmakePresetArguments("workflow", "ci"));
        assertThrows(IllegalArgumentException.class, () -> JobQuickfixController.cmakePresetArguments("build", "debug\nother"));

        Path workspace = Files.createDirectories(temporaryDirectory.resolve("presets"));
        assertFalse(JobQuickfixController.hasCmakePresetFile(workspace));
        Files.writeString(workspace.resolve("CMakeUserPresets.json"), "{}\n");
        assertTrue(JobQuickfixController.hasCmakePresetFile(workspace));
    }

    @Test
    void detectsGradleWrapperCargoAndGoModuleTaskFallbacks() throws Exception {
        Path gradle = Files.createDirectories(temporaryDirectory.resolve("gradle"));
        Files.writeString(gradle.resolve("gradlew"), "wrapper");
        Path cargo = Files.createDirectories(temporaryDirectory.resolve("cargo"));
        Files.writeString(cargo.resolve("Cargo.toml"), "[package]\nname = \"example\"\n");
        Path go = Files.createDirectories(temporaryDirectory.resolve("go"));
        Files.writeString(go.resolve("go.mod"), "module example.com/example\n");
        JobQuickfixController controller = new JobQuickfixController(null);

        assertEquals("./gradlew test", controller.inferBuiltInTaskCommand("test", gradle.toFile()));
        assertEquals("./gradlew build", controller.inferBuiltInTaskCommand("build", gradle.toFile()));
        assertEquals("cargo test", controller.inferBuiltInTaskCommand("test", cargo.toFile()));
        assertEquals("cargo build", controller.inferBuiltInTaskCommand("build", cargo.toFile()));
        assertEquals("go test ./...", controller.inferBuiltInTaskCommand("test", go.toFile()));
        assertEquals("go build ./...", controller.inferBuiltInTaskCommand("build", go.toFile()));
    }

    @Test
    void explicitImportedDefaultBuildTaskPrecedesConventionalFallback() throws Exception {
        Path workspace = Files.createDirectories(temporaryDirectory.resolve("explicit-default-build"));
        Files.writeString(workspace.resolve("Makefile"), "build:\n\t@true\n");
        TaskService.WorkspaceTask imported = TaskService.withGroup(TaskService.directWorkspaceTask("vscode-project-build", List.of("make", "project-build"),
            "${workspaceFolder}", java.util.Map.of(), TaskService.ProblemMatcher.NONE, TaskService.Presentation.NEVER),
            TaskService.TaskGroup.BUILD, true);

        TaskService.WorkspaceTask selected = new JobQuickfixController(null).resolveTask("build", workspace.toFile(), java.util.Map.of(imported.name(), imported));

        assertEquals(imported, selected);
    }

    @Test
    void dotnetFallbackRequiresExactlyOneTopLevelProjectOrSolution() throws Exception {
        Path workspace = Files.createDirectories(temporaryDirectory.resolve("dotnet workspace"));
        Files.writeString(workspace.resolve("app.slnx"), "<Solution/>\n");
        JobQuickfixController controller = new JobQuickfixController(null);

        TaskService.WorkspaceTask test = controller.inferBuiltInTask("test", workspace.toFile());
        TaskService.WorkspaceTask build = controller.inferBuiltInTask("build", workspace.toFile());

        assertEquals(List.of("dotnet", "test"), test.directArguments());
        assertEquals(List.of("dotnet", "build"), build.directArguments());
        assertEquals(TaskService.ShellPolicy.DIRECT, test.shell());

        Files.writeString(workspace.resolve("app.csproj"), "<Project/>\n");
        assertNull(controller.inferBuiltInTask("test", workspace.toFile()));
        assertNull(controller.inferBuiltInTask("build", workspace.toFile()));
    }
}
