[mode.insert]
"Left" = "editor.moveLeft"
"Right" = "editor.moveRight"
"Cmd-Left" = "editor.moveLineStart"
"Cmd-Right" = "editor.moveLineEnd"
"Cmd-N" = "file.new"
"Cmd-O" = "file.open"
"Cmd-Shift-N" = "file.newWindow"
"Cmd-S" = "file.save"
"Cmd-W" = "pane.close"
"Cmd-," = "app.settings"
"Cmd-P" = "nav.gotoFile"
"Cmd-Shift-P" = "view.commandPalette"
"Cmd-K Cmd-S" = "app.keyboardShortcuts"
"Cmd-B" = "view.sidebar.toggle"
"Cmd-J" = "terminal.toggle"
"Cmd-Shift-." = "view.hiddenFiles.toggle"
"Ctrl-Tab" = "file.nextBuffer"
"Ctrl-Shift-Tab" = "file.previousBuffer"
"Cmd-1" = "file.selectTab.1"
"Cmd-2" = "file.selectTab.2"
"Cmd-3" = "file.selectTab.3"
"Cmd-4" = "file.selectTab.4"
"Cmd-5" = "file.selectTab.5"
"Cmd-6" = "file.selectTab.6"
"Cmd-7" = "file.selectTab.7"
"Cmd-8" = "file.selectTab.8"
"Cmd-9" = "file.selectTab.9"
"Cmd-\\" = "pane.splitHorizontal"
"Cmd-Opt-\\" = "pane.splitVertical"
"Cmd-Opt-Left" = "pane.focusLeft"
"Cmd-Opt-Right" = "pane.focusRight"
"Cmd-Opt-Up" = "pane.focusUp"
"Cmd-Opt-Down" = "pane.focusDown"
"Cmd-F" = "edit.find"
"Cmd-G" = "edit.findNext"
"Cmd-Shift-G" = "edit.findPrevious"
"Cmd-Ctrl-G" = "edit.selectAllFindMatches"
"Ctrl-G" = "nav.gotoLine"
"Cmd-D" = "editor.addNextSelection"
"Cmd-Shift-F" = "edit.findInProject"
"Cmd-T" = "nav.gotoSymbolWorkspace"
"Cmd-Shift-O" = "nav.gotoSymbolFile"
"Cmd-Opt-7" = "view.outline"
"Ctrl-Alt-N" = "problems.next"
"Ctrl-Alt-P" = "problems.previous"
"Ctrl-Space" = "lsp.completion"
"Shift-Opt-F" = "lsp.formatDocument"
"Cmd-." = "lsp.codeAction"
