[mode.insert]
"Left" = "editor.moveLeft"
"Right" = "editor.moveRight"
"Cmd-Left" = "editor.moveLineStart"
"Cmd-Right" = "editor.moveLineEnd"
"Cmd-S" = "file.save"
"Cmd-W" = "pane.close"
"Cmd-\\" = "pane.splitHorizontal"
"Cmd-Opt-\\" = "pane.splitVertical"
"Cmd-Opt-Left" = "pane.focusLeft"
"Cmd-Opt-Right" = "pane.focusRight"
"Cmd-Opt-Up" = "pane.focusUp"
"Cmd-Opt-Down" = "pane.focusDown"
"Cmd-F" = "edit.find"
"Cmd-G" = "edit.findNext"
"Cmd-Shift-G" = "edit.findPrevious"
"Cmd-Ctrl-G" = "edit.selectAllFindMatches"
"Cmd-D" = "editor.addNextSelection"
"Cmd-Shift-F" = "edit.findInProject"
"Cmd-T" = "nav.gotoSymbolWorkspace"
"Cmd-Shift-O" = "nav.gotoSymbolFile"
