[mode.normal]
"h" = "editor.moveLeft"
"j" = "editor.moveDown"
"k" = "editor.moveUp"
"l" = "editor.moveRight"
"w" = "editor.moveWordForward"
"Shift-W" = "editor.moveBigWordForward"
"b" = "editor.moveWordBackward"
"Shift-B" = "editor.moveBigWordBackward"
"e" = "editor.moveWordEnd"
"Shift-E" = "editor.moveBigWordEnd"
"0" = "editor.moveLineStart"
"Shift-6" = "editor.moveLineStart"
"Shift-4" = "editor.moveLineEnd"
"gg" = "editor.moveBufferStart"
"Shift-G" = "editor.moveBufferEnd"
"Shift-[" = "editor.moveParagraphBackward"
"Shift-]" = "editor.moveParagraphForward"
"f" = "editor.findCharForward"
"Shift-F" = "editor.findCharBackward"
"t" = "editor.tillCharForward"
"Shift-T" = "editor.tillCharBackward"
";" = "editor.repeatCharFind"
"," = "editor.repeatCharFindReverse"
"d" = "vim.operator.delete"
"c" = "vim.operator.change"
"y" = "vim.operator.yank"
"Shift-'" = "vim.registerPrefix"
"''" = "vim.jumpBack"
"q" = "vim.macro.recordPrefix"
"Shift-2" = "vim.macro.replayPrefix"
"p" = "vim.pasteAfter"
"Shift-P" = "vim.pasteBefore"
"v" = "vim.visual.char"
"Shift-V" = "vim.visual.line"
"Ctrl-V" = "vim.visual.block"
"Shift-;" = "vim.ex.start"
"u" = "edit.undo"
"Ctrl-R" = "edit.redo"
"Cmd-D" = "editor.addNextSelection"
"Cmd-Ctrl-G" = "edit.selectAllFindMatches"
"Cmd-W" = "pane.close"
"Cmd-\\" = "pane.splitHorizontal"
"Cmd-Opt-\\" = "pane.splitVertical"
"Cmd-Opt-Left" = "pane.focusLeft"
"Cmd-Opt-Right" = "pane.focusRight"
"Cmd-Opt-Up" = "pane.focusUp"
"Cmd-Opt-Down" = "pane.focusDown"
"Cmd-T" = "nav.gotoSymbolWorkspace"
"Cmd-Shift-O" = "nav.gotoSymbolFile"
"i" = "mode.insert"
"/" = "vim.searchForward"
"Shift-/" = "vim.searchBackward"
"n" = "edit.findNext"
"Shift-N" = "edit.findPrevious"

[mode.visual]
"Cmd-D" = "editor.addNextSelection"
"Cmd-Ctrl-G" = "edit.selectAllFindMatches"
"Cmd-W" = "pane.close"
"Cmd-\\" = "pane.splitHorizontal"
"Cmd-Opt-\\" = "pane.splitVertical"
"Cmd-Opt-Left" = "pane.focusLeft"
"Cmd-Opt-Right" = "pane.focusRight"
"Cmd-Opt-Up" = "pane.focusUp"
"Cmd-Opt-Down" = "pane.focusDown"
"Cmd-T" = "nav.gotoSymbolWorkspace"
"Cmd-Shift-O" = "nav.gotoSymbolFile"
"Esc" = "mode.normal"
"h" = "editor.moveLeft"
"j" = "editor.moveDown"
"k" = "editor.moveUp"
"l" = "editor.moveRight"
"w" = "editor.moveWordForward"
"b" = "editor.moveWordBackward"
"e" = "editor.moveWordEnd"
"0" = "editor.moveLineStart"
"Shift-4" = "editor.moveLineEnd"
"d" = "vim.operator.delete"
"c" = "vim.operator.change"
"y" = "vim.operator.yank"

[mode.operatorPending]
"h" = "editor.moveLeft"
"j" = "editor.moveDown"
"k" = "editor.moveUp"
"l" = "editor.moveRight"
"w" = "editor.moveWordForward"
"Shift-W" = "editor.moveBigWordForward"
"b" = "editor.moveWordBackward"
"Shift-B" = "editor.moveBigWordBackward"
"e" = "editor.moveWordEnd"
"Shift-E" = "editor.moveBigWordEnd"
"0" = "editor.moveLineStart"
"Shift-6" = "editor.moveLineStart"
"Shift-4" = "editor.moveLineEnd"
"d" = "vim.operator.line.delete"
"c" = "vim.operator.line.change"
"y" = "vim.operator.line.yank"
"iw" = "vim.textObject.innerWord"
"aw" = "vim.textObject.aroundWord"
"i Shift-'" = "vim.textObject.innerDoubleQuote"
"a Shift-'" = "vim.textObject.aroundDoubleQuote"
"i '" = "vim.textObject.innerSingleQuote"
"a '" = "vim.textObject.aroundSingleQuote"
"i Shift-9" = "vim.textObject.innerParen"
"a Shift-9" = "vim.textObject.aroundParen"
"i [" = "vim.textObject.innerBracket"
"a [" = "vim.textObject.aroundBracket"
"i Shift-[" = "vim.textObject.innerBrace"
"a Shift-[" = "vim.textObject.aroundBrace"
"ip" = "vim.textObject.innerParagraph"
"ap" = "vim.textObject.aroundParagraph"

[mode.insert]
"Cmd-D" = "editor.addNextSelection"
"Cmd-Ctrl-G" = "edit.selectAllFindMatches"
"Cmd-W" = "pane.close"
"Cmd-\\" = "pane.splitHorizontal"
"Cmd-Opt-\\" = "pane.splitVertical"
"Cmd-Opt-Left" = "pane.focusLeft"
"Cmd-Opt-Right" = "pane.focusRight"
"Cmd-Opt-Up" = "pane.focusUp"
"Cmd-Opt-Down" = "pane.focusDown"
"Cmd-T" = "nav.gotoSymbolWorkspace"
"Cmd-Shift-O" = "nav.gotoSymbolFile"
"Esc" = "mode.normal"
"jk" = "mode.normal"
