[mode.emacs]
"C-f" = "editor.moveRight"
"C-b" = "editor.moveLeft"
"C-n" = "editor.moveDown"
"C-p" = "editor.moveUp"
"Left" = "editor.moveLeft"
"Right" = "editor.moveRight"
"Up" = "editor.moveUp"
"Down" = "editor.moveDown"
"Shift-Left" = "editor.extendLeft"
"Shift-Right" = "editor.extendRight"
"Shift-Up" = "editor.extendUp"
"Shift-Down" = "editor.extendDown"
"C-a" = "editor.moveLineStart"
"C-e" = "editor.moveLineEnd"
"M-f" = "editor.moveWordForward"
"M-b" = "editor.moveWordBackward"
"M-<" = "editor.moveBufferStart"
"M->" = "editor.moveBufferEnd"
"C-w" = "emacs.killRegion"
"M-w" = "emacs.copyRegion"
"C-y" = "emacs.yank"
"M-y" = "emacs.yankPop"
"C-t" = "emacs.transposeChars"
"M-t" = "emacs.transposeWords"
"M-u" = "emacs.uppercaseWord"
"M-l" = "emacs.lowercaseWord"
"M-c" = "emacs.capitalizeWord"
"C-M-f" = "emacs.forwardSexp"
"C-M-b" = "emacs.backwardSexp"
"C-M-k" = "emacs.killSexp"
"C-M-Space" = "emacs.markSexp"
"C-/" = "edit.undo"
"C-_" = "edit.redo"
"Cmd-D" = "editor.addNextSelection"
"Cmd-Ctrl-G" = "edit.selectAllFindMatches"
"Cmd-W" = "pane.close"
"Cmd-\\" = "pane.splitHorizontal"
"Cmd-Opt-\\" = "pane.splitVertical"
"Cmd-Opt-Left" = "pane.focusLeft"
"Cmd-Opt-Right" = "pane.focusRight"
"Cmd-Opt-Up" = "pane.focusUp"
"Cmd-Opt-Down" = "pane.focusDown"
"Cmd-T" = "nav.gotoSymbolWorkspace"
"Cmd-Shift-O" = "nav.gotoSymbolFile"
"Cmd-Opt-7" = "view.outline"
"Ctrl-Alt-N" = "problems.next"
"Ctrl-Alt-P" = "problems.previous"
"Ctrl-Space" = "emacs.setMark"
"C-s" = "emacs.isearchForward"
"C-r" = "emacs.isearchBackward"
"C-x C-s" = "file.save"
"C-x C-f" = "nav.gotoFile"
"C-x C-c" = "app.quit"
"C-x C-x" = "emacs.exchangePointMark"
"C-x b" = "file.nextBuffer"
"C-x k" = "file.close"
"C-x 0" = "pane.close"
"C-x 1" = "pane.closeOthers"
"C-x 2" = "pane.splitHorizontal"
"C-x 3" = "pane.splitVertical"
"C-x o" = "pane.focusNext"
"C-x Shift-9" = "emacs.macro.start"
"C-x Shift-0" = "emacs.macro.end"
"C-x e" = "emacs.macro.run"
"C-x r k" = "emacs.rectangle.kill"
"C-x r y" = "emacs.rectangle.yank"
"C-x r t" = "emacs.rectangle.string"
"M-x" = "view.commandPalette"
"M-g g" = "nav.gotoLine"
"M-Shift-5" = "emacs.queryReplace"
