# Catppuccin Mocha palette by Catppuccin.
# Source: https://catppuccin.com/
# License: MIT.
"comment" = "#9399B2"
"comment.documentation" = "#9399B2"
"keyword" = "#CBA6F7"
"keyword.control" = "#CBA6F7"
"keyword.function" = "#CBA6F7"
"keyword.operator" = "#CBA6F7"
"keyword.return" = "#CBA6F7"
"string" = "#A6E3A1"
"string.escape" = "#FAB387"
"string.regexp" = "#F5C2E7"
"string.special" = "#A6E3A1"
"type" = "#F9E2AF"
"type.builtin" = "#F9E2AF"
"type.parameter" = "#F9E2AF"
"function" = "#89B4FA"
"function.builtin" = "#89B4FA"
"function.macro" = "#89B4FA"
"function.method" = "#89B4FA"
"variable" = "#CDD6F4"
"variable.builtin" = "#FAB387"
"variable.member" = "#94E2D5"
"variable.parameter" = "#CDD6F4"
"parameter" = "#CDD6F4"
"constant" = "#FAB387"
"constant.builtin" = "#FAB387"
"constant.macro" = "#FAB387"
"number" = "#F5C2E7"
"number.float" = "#F5C2E7"
"boolean" = "#FAB387"
"character" = "#A6E3A1"
"character.special" = "#FAB387"
"operator" = "#CDD6F4"
"punctuation" = "#CDD6F4"
"punctuation.bracket" = "#CDD6F4"
"punctuation.delimiter" = "#CDD6F4"
"punctuation.special" = "#FAB387"
"attribute" = "#F9E2AF"
"tag" = "#89B4FA"
"label" = "#F9E2AF"
"namespace" = "#94E2D5"
"module" = "#94E2D5"
"property" = "#94E2D5"
"field" = "#94E2D5"
"error" = "#F38BA8"
"diff.plus" = "#A6E3A1"
"diff.minus" = "#F38BA8"
"markup.heading" = "#89B4FA"
"markup.link" = "#89B4FA"
"markup.list" = "#F9E2AF"
"markup.bold" = "#CDD6F4"
"markup.italic" = "#CDD6F4"
"markup.raw" = "#A6E3A1"
"markup.quote" = "#9399B2"
