# Catppuccin Latte palette by Catppuccin.
# Source: https://catppuccin.com/
# License: MIT.
"comment" = "#7C7F93"
"comment.documentation" = "#7C7F93"
"keyword" = "#8839EF"
"keyword.control" = "#8839EF"
"keyword.function" = "#8839EF"
"keyword.operator" = "#8839EF"
"keyword.return" = "#8839EF"
"string" = "#40A02B"
"string.escape" = "#FE640B"
"string.regexp" = "#EA76CB"
"string.special" = "#40A02B"
"type" = "#DF8E1D"
"type.builtin" = "#DF8E1D"
"type.parameter" = "#DF8E1D"
"function" = "#1E66F5"
"function.builtin" = "#1E66F5"
"function.macro" = "#1E66F5"
"function.method" = "#1E66F5"
"variable" = "#4C4F69"
"variable.builtin" = "#FE640B"
"variable.member" = "#179299"
"variable.parameter" = "#4C4F69"
"parameter" = "#4C4F69"
"constant" = "#FE640B"
"constant.builtin" = "#FE640B"
"constant.macro" = "#FE640B"
"number" = "#EA76CB"
"number.float" = "#EA76CB"
"boolean" = "#FE640B"
"character" = "#40A02B"
"character.special" = "#FE640B"
"operator" = "#4C4F69"
"punctuation" = "#4C4F69"
"punctuation.bracket" = "#4C4F69"
"punctuation.delimiter" = "#4C4F69"
"punctuation.special" = "#FE640B"
"attribute" = "#DF8E1D"
"tag" = "#1E66F5"
"label" = "#DF8E1D"
"namespace" = "#179299"
"module" = "#179299"
"property" = "#179299"
"field" = "#179299"
"error" = "#D20F39"
"diff.plus" = "#40A02B"
"diff.minus" = "#D20F39"
"markup.heading" = "#1E66F5"
"markup.link" = "#1E66F5"
"markup.list" = "#DF8E1D"
"markup.bold" = "#4C4F69"
"markup.italic" = "#4C4F69"
"markup.raw" = "#40A02B"
"markup.quote" = "#7C7F93"
