"comment" = "#008000"
"keyword" = "#AF00DB"
"string" = "#A31515"
"type" = "#267F99"
"type.builtin" = "#267F99"
"function" = "#795E26"
"variable" = "#001080"
"variable.parameter" = "#001080"
"constant" = "#0070C1"
"number" = "#098658"
"operator" = "#000000"
"punctuation" = "#000000"
