"comment" = "#6A9955"
"comment.documentation" = "#6A9955"
"keyword" = "#C586C0"
"keyword.control" = "#C586C0"
"keyword.function" = "#C586C0"
"keyword.operator" = "#C586C0"
"keyword.return" = "#C586C0"
"string" = "#CE9178"
"string.escape" = "#D7BA7D"
"string.regexp" = "#D16969"
"string.special" = "#CE9178"
"type" = "#4EC9B0"
"type.builtin" = "#4EC9B0"
"type.parameter" = "#4EC9B0"
"function" = "#DCDCAA"
"function.builtin" = "#DCDCAA"
"function.macro" = "#DCDCAA"
"function.method" = "#DCDCAA"
"variable" = "#D4D4D4"
"variable.builtin" = "#D4D4D4"
"variable.member" = "#9CDCFE"
"variable.parameter" = "#9CDCFE"
"parameter" = "#9CDCFE"
"constant" = "#4FC1FF"
"constant.builtin" = "#4FC1FF"
"constant.macro" = "#4FC1FF"
"number" = "#B5CEA8"
"number.float" = "#B5CEA8"
"boolean" = "#569CD6"
"character" = "#CE9178"
"character.special" = "#D7BA7D"
"operator" = "#D4D4D4"
"punctuation" = "#D4D4D4"
"punctuation.bracket" = "#D4D4D4"
"punctuation.delimiter" = "#D4D4D4"
"punctuation.special" = "#D7BA7D"
"attribute" = "#9CDCFE"
"tag" = "#569CD6"
"label" = "#D4D4D4"
"namespace" = "#4EC9B0"
"module" = "#4EC9B0"
"property" = "#9CDCFE"
"field" = "#9CDCFE"
"error" = "#F44747"
"diff.plus" = "#6A9955"
"diff.minus" = "#F44747"
"markup.heading" = "#569CD6"
"markup.link" = "#3794FF"
"markup.list" = "#D7BA7D"
"markup.bold" = "#D4D4D4"
"markup.italic" = "#D4D4D4"
"markup.raw" = "#CE9178"
"markup.quote" = "#6A9955"
