# Gruvbox palette by Pavel Pertsev (morhetz).
# Source: https://github.com/morhetz/gruvbox
# License: MIT/X11.
"comment" = "#928374"
"comment.documentation" = "#928374"
"keyword" = "#9D0006"
"keyword.control" = "#9D0006"
"keyword.function" = "#9D0006"
"keyword.operator" = "#9D0006"
"keyword.return" = "#9D0006"
"string" = "#79740E"
"string.escape" = "#AF3A03"
"string.regexp" = "#8F3F71"
"string.special" = "#79740E"
"type" = "#B57614"
"type.builtin" = "#B57614"
"type.parameter" = "#B57614"
"function" = "#076678"
"function.builtin" = "#076678"
"function.macro" = "#076678"
"function.method" = "#076678"
"variable" = "#3C3836"
"variable.builtin" = "#AF3A03"
"variable.member" = "#427B58"
"variable.parameter" = "#3C3836"
"parameter" = "#3C3836"
"constant" = "#AF3A03"
"constant.builtin" = "#AF3A03"
"constant.macro" = "#AF3A03"
"number" = "#8F3F71"
"number.float" = "#8F3F71"
"boolean" = "#AF3A03"
"character" = "#79740E"
"character.special" = "#AF3A03"
"operator" = "#3C3836"
"punctuation" = "#3C3836"
"punctuation.bracket" = "#3C3836"
"punctuation.delimiter" = "#3C3836"
"punctuation.special" = "#AF3A03"
"attribute" = "#B57614"
"tag" = "#076678"
"label" = "#B57614"
"namespace" = "#427B58"
"module" = "#427B58"
"property" = "#427B58"
"field" = "#427B58"
"error" = "#9D0006"
"diff.plus" = "#79740E"
"diff.minus" = "#9D0006"
"markup.heading" = "#076678"
"markup.link" = "#076678"
"markup.list" = "#B57614"
"markup.bold" = "#3C3836"
"markup.italic" = "#3C3836"
"markup.raw" = "#79740E"
"markup.quote" = "#928374"
