# Gruvbox palette by Pavel Pertsev (morhetz).
# Source: https://github.com/morhetz/gruvbox
# License: MIT/X11.
"comment" = "#928374"
"comment.documentation" = "#928374"
"keyword" = "#FB4934"
"keyword.control" = "#FB4934"
"keyword.function" = "#FB4934"
"keyword.operator" = "#FB4934"
"keyword.return" = "#FB4934"
"string" = "#B8BB26"
"string.escape" = "#FE8019"
"string.regexp" = "#D3869B"
"string.special" = "#B8BB26"
"type" = "#FABD2F"
"type.builtin" = "#FABD2F"
"type.parameter" = "#FABD2F"
"function" = "#83A598"
"function.builtin" = "#83A598"
"function.macro" = "#83A598"
"function.method" = "#83A598"
"variable" = "#EBDBB2"
"variable.builtin" = "#FE8019"
"variable.member" = "#8EC07C"
"variable.parameter" = "#EBDBB2"
"parameter" = "#EBDBB2"
"constant" = "#FE8019"
"constant.builtin" = "#FE8019"
"constant.macro" = "#FE8019"
"number" = "#D3869B"
"number.float" = "#D3869B"
"boolean" = "#FE8019"
"character" = "#B8BB26"
"character.special" = "#FE8019"
"operator" = "#EBDBB2"
"punctuation" = "#EBDBB2"
"punctuation.bracket" = "#EBDBB2"
"punctuation.delimiter" = "#EBDBB2"
"punctuation.special" = "#FE8019"
"attribute" = "#FABD2F"
"tag" = "#83A598"
"label" = "#FABD2F"
"namespace" = "#8EC07C"
"module" = "#8EC07C"
"property" = "#8EC07C"
"field" = "#8EC07C"
"error" = "#FB4934"
"diff.plus" = "#B8BB26"
"diff.minus" = "#FB4934"
"markup.heading" = "#83A598"
"markup.link" = "#83A598"
"markup.list" = "#FABD2F"
"markup.bold" = "#EBDBB2"
"markup.italic" = "#EBDBB2"
"markup.raw" = "#B8BB26"
"markup.quote" = "#928374"
