# Nord palette by Arctic Ice Studio.
# Source: https://www.nordtheme.com/
# License: MIT.
"comment" = "#616E88"
"comment.documentation" = "#616E88"
"keyword" = "#81A1C1"
"keyword.control" = "#81A1C1"
"keyword.function" = "#81A1C1"
"keyword.operator" = "#81A1C1"
"keyword.return" = "#81A1C1"
"string" = "#A3BE8C"
"string.escape" = "#D08770"
"string.regexp" = "#B48EAD"
"string.special" = "#A3BE8C"
"type" = "#8FBCBB"
"type.builtin" = "#8FBCBB"
"type.parameter" = "#8FBCBB"
"function" = "#88C0D0"
"function.builtin" = "#88C0D0"
"function.macro" = "#88C0D0"
"function.method" = "#88C0D0"
"variable" = "#D8DEE9"
"variable.builtin" = "#D08770"
"variable.member" = "#88C0D0"
"variable.parameter" = "#D8DEE9"
"parameter" = "#D8DEE9"
"constant" = "#D08770"
"constant.builtin" = "#D08770"
"constant.macro" = "#D08770"
"number" = "#B48EAD"
"number.float" = "#B48EAD"
"boolean" = "#D08770"
"character" = "#A3BE8C"
"character.special" = "#D08770"
"operator" = "#D8DEE9"
"punctuation" = "#D8DEE9"
"punctuation.bracket" = "#D8DEE9"
"punctuation.delimiter" = "#D8DEE9"
"punctuation.special" = "#D08770"
"attribute" = "#EBCB8B"
"tag" = "#81A1C1"
"label" = "#EBCB8B"
"namespace" = "#8FBCBB"
"module" = "#8FBCBB"
"property" = "#88C0D0"
"field" = "#88C0D0"
"error" = "#BF616A"
"diff.plus" = "#A3BE8C"
"diff.minus" = "#BF616A"
"markup.heading" = "#81A1C1"
"markup.link" = "#88C0D0"
"markup.list" = "#EBCB8B"
"markup.bold" = "#D8DEE9"
"markup.italic" = "#D8DEE9"
"markup.raw" = "#A3BE8C"
"markup.quote" = "#616E88"
