# Solarized palette by Ethan Schoonover.
# Source: https://ethanschoonover.com/solarized/
# License: MIT/Expat.
"comment" = "#93A1A1"
"comment.documentation" = "#93A1A1"
"keyword" = "#859900"
"keyword.control" = "#859900"
"keyword.function" = "#859900"
"keyword.operator" = "#859900"
"keyword.return" = "#859900"
"string" = "#2AA198"
"string.escape" = "#CB4B16"
"string.regexp" = "#D33682"
"string.special" = "#2AA198"
"type" = "#B58900"
"type.builtin" = "#B58900"
"type.parameter" = "#B58900"
"function" = "#268BD2"
"function.builtin" = "#268BD2"
"function.macro" = "#268BD2"
"function.method" = "#268BD2"
"variable" = "#657B83"
"variable.builtin" = "#CB4B16"
"variable.member" = "#268BD2"
"variable.parameter" = "#657B83"
"parameter" = "#657B83"
"constant" = "#CB4B16"
"constant.builtin" = "#CB4B16"
"constant.macro" = "#CB4B16"
"number" = "#D33682"
"number.float" = "#D33682"
"boolean" = "#CB4B16"
"character" = "#2AA198"
"character.special" = "#CB4B16"
"operator" = "#657B83"
"punctuation" = "#657B83"
"punctuation.bracket" = "#657B83"
"punctuation.delimiter" = "#657B83"
"punctuation.special" = "#CB4B16"
"attribute" = "#B58900"
"tag" = "#268BD2"
"label" = "#B58900"
"namespace" = "#2AA198"
"module" = "#2AA198"
"property" = "#268BD2"
"field" = "#268BD2"
"error" = "#DC322F"
"diff.plus" = "#859900"
"diff.minus" = "#DC322F"
"markup.heading" = "#268BD2"
"markup.link" = "#268BD2"
"markup.list" = "#B58900"
"markup.bold" = "#657B83"
"markup.italic" = "#657B83"
"markup.raw" = "#2AA198"
"markup.quote" = "#93A1A1"
