# Tokyo Night palette by enkia / Tokyo Night VS Code theme.
# Source: https://github.com/tokyo-night/tokyo-night-vscode-theme
# License: MIT.
"comment" = "#565F89"
"comment.documentation" = "#565F89"
"keyword" = "#BB9AF7"
"keyword.control" = "#BB9AF7"
"keyword.function" = "#BB9AF7"
"keyword.operator" = "#BB9AF7"
"keyword.return" = "#BB9AF7"
"string" = "#9ECE6A"
"string.escape" = "#FF9E64"
"string.regexp" = "#BB9AF7"
"string.special" = "#9ECE6A"
"type" = "#E0AF68"
"type.builtin" = "#E0AF68"
"type.parameter" = "#E0AF68"
"function" = "#7AA2F7"
"function.builtin" = "#7AA2F7"
"function.macro" = "#7AA2F7"
"function.method" = "#7AA2F7"
"variable" = "#C0CAF5"
"variable.builtin" = "#FF9E64"
"variable.member" = "#7DCFFF"
"variable.parameter" = "#C0CAF5"
"parameter" = "#C0CAF5"
"constant" = "#FF9E64"
"constant.builtin" = "#FF9E64"
"constant.macro" = "#FF9E64"
"number" = "#BB9AF7"
"number.float" = "#BB9AF7"
"boolean" = "#FF9E64"
"character" = "#9ECE6A"
"character.special" = "#FF9E64"
"operator" = "#C0CAF5"
"punctuation" = "#C0CAF5"
"punctuation.bracket" = "#C0CAF5"
"punctuation.delimiter" = "#C0CAF5"
"punctuation.special" = "#FF9E64"
"attribute" = "#E0AF68"
"tag" = "#7AA2F7"
"label" = "#E0AF68"
"namespace" = "#7DCFFF"
"module" = "#7DCFFF"
"property" = "#7DCFFF"
"field" = "#7DCFFF"
"error" = "#F7768E"
"diff.plus" = "#9ECE6A"
"diff.minus" = "#F7768E"
"markup.heading" = "#7AA2F7"
"markup.link" = "#7AA2F7"
"markup.list" = "#E0AF68"
"markup.bold" = "#C0CAF5"
"markup.italic" = "#C0CAF5"
"markup.raw" = "#9ECE6A"
"markup.quote" = "#565F89"
