import Foundation

struct CodepointRange {
	var lower: UInt32
	var upper: UInt32
	var value: String
}

let arguments = CommandLine.arguments
guard arguments.count == 2 else {
	fputs("usage: swift scripts/gen_grapheme_tables.swift <ucd-dir>\n", stderr)
	exit(64)
}

let directory = URL(fileURLWithPath: arguments[1], isDirectory: true)

let graphemeValues: [String: UInt8] = [
	"Other": 0,
	"CR": 1,
	"LF": 2,
	"Control": 3,
	"Extend": 4,
	"ZWJ": 5,
	"Regional_Indicator": 6,
	"Prepend": 7,
	"SpacingMark": 8,
	"L": 9,
	"V": 10,
	"T": 11,
	"LV": 12,
	"LVT": 13,
]

let indicValues: [String: UInt8] = [
	"None": 0,
	"Extend": 1,
	"Linker": 2,
	"Consonant": 3,
]

func readLines(_ name: String) throws -> [String] {
	let url = directory.appendingPathComponent(name)
	return try String(contentsOf: url, encoding: .utf8).split(separator: "\n", omittingEmptySubsequences: false).map(String.init)
}

func strippedFields(_ line: String) -> [String] {
	let data = line.split(separator: "#", maxSplits: 1, omittingEmptySubsequences: false)[0]
	return data.split(separator: ";").map { $0.trimmingCharacters(in: .whitespaces) }.filter { !$0.isEmpty }
}

func parseRange(_ text: String) throws -> (UInt32, UInt32) {
	let parts = text.split(separator: ".", omittingEmptySubsequences: true)
	guard let lower = UInt32(parts[0], radix: 16) else {
		throw NSError(domain: "gen_grapheme_tables", code: 1, userInfo: [NSLocalizedDescriptionKey: "bad codepoint range \(text)"])
	}
	if parts.count == 1 {
		return (lower, lower)
	}
	guard parts.count == 2, let upper = UInt32(parts[1], radix: 16) else {
		throw NSError(domain: "gen_grapheme_tables", code: 1, userInfo: [NSLocalizedDescriptionKey: "bad codepoint range \(text)"])
	}
	return (lower, upper)
}

func parseGraphemeBreakProperty() throws -> [CodepointRange] {
	var ranges: [CodepointRange] = []
	for line in try readLines("GraphemeBreakProperty.txt") {
		let fields = strippedFields(line)
		guard fields.count >= 2 else {
			continue
		}
		guard graphemeValues[fields[1]] != nil else {
			throw NSError(domain: "gen_grapheme_tables", code: 1, userInfo: [NSLocalizedDescriptionKey: "unknown GCB property \(fields[1])"])
		}
		let range = try parseRange(fields[0])
		ranges.append(CodepointRange(lower: range.0, upper: range.1, value: fields[1]))
	}
	return coalesced(ranges)
}

func parseExtendedPictographic() throws -> [CodepointRange] {
	var ranges: [CodepointRange] = []
	for line in try readLines("emoji-data.txt") {
		let fields = strippedFields(line)
		guard fields.count >= 2, fields[1] == "Extended_Pictographic" else {
			continue
		}
		let range = try parseRange(fields[0])
		ranges.append(CodepointRange(lower: range.0, upper: range.1, value: "Extended_Pictographic"))
	}
	return coalesced(ranges)
}

func parseIndicConjunctBreak() throws -> [CodepointRange] {
	var ranges: [CodepointRange] = []
	for line in try readLines("DerivedCoreProperties.txt") {
		let fields = strippedFields(line)
		guard fields.count >= 3, fields[1] == "InCB" else {
			continue
		}
		guard indicValues[fields[2]] != nil else {
			throw NSError(domain: "gen_grapheme_tables", code: 1, userInfo: [NSLocalizedDescriptionKey: "unknown InCB property \(fields[2])"])
		}
		let range = try parseRange(fields[0])
		ranges.append(CodepointRange(lower: range.0, upper: range.1, value: fields[2]))
	}
	return coalesced(ranges)
}

func coalesced(_ ranges: [CodepointRange]) -> [CodepointRange] {
	let sorted = ranges.sorted {
		if $0.lower == $1.lower {
			return $0.upper < $1.upper
		}
		return $0.lower < $1.lower
	}
	var result: [CodepointRange] = []
	for range in sorted {
		if var last = result.last, last.value == range.value, last.upper + 1 == range.lower {
			last.upper = range.upper
			result[result.count - 1] = last
		} else {
			result.append(range)
		}
	}
	return result
}

func hex(_ value: UInt32) -> String {
	"0x" + String(value, radix: 16, uppercase: true)
}

func emitRanges(_ name: String, _ ranges: [CodepointRange], values: [String: UInt8]) {
	print("\tprivate static let \(name): [RangeRecord] = [")
	for range in ranges {
		let value = values[range.value] ?? 1
		print("\t\tRangeRecord(\(hex(range.lower)), \(hex(range.upper)), \(value)),")
	}
	print("\t]")
}

let graphemeRanges = try parseGraphemeBreakProperty()
let extendedPictographicRanges = try parseExtendedPictographic()
let indicRanges = try parseIndicConjunctBreak()

print("""
// generated by scripts/gen_grapheme_tables.swift from Unicode 17.0.0 UCD. Do not edit.

internal enum UAX29GraphemeBreakProperty: UInt8, Sendable {
\tcase other = 0
\tcase cr = 1
\tcase lf = 2
\tcase control = 3
\tcase extend = 4
\tcase zwj = 5
\tcase regionalIndicator = 6
\tcase prepend = 7
\tcase spacingMark = 8
\tcase l = 9
\tcase v = 10
\tcase t = 11
\tcase lv = 12
\tcase lvt = 13
}

internal enum UAX29IndicConjunctBreak: UInt8, Sendable {
\tcase none = 0
\tcase extend = 1
\tcase linker = 2
\tcase consonant = 3
}

internal enum UAX29GraphemeTables {
\tprivate struct RangeRecord: Sendable {
\t\tvar lower: UInt32
\t\tvar upper: UInt32
\t\tvar value: UInt8

\t\tinit(_ lower: UInt32, _ upper: UInt32, _ value: UInt8) {
\t\t\tself.lower = lower
\t\t\tself.upper = upper
\t\t\tself.value = value
\t\t}
\t}

\tstatic func graphemeBreakProperty(for scalar: UInt32) -> UAX29GraphemeBreakProperty {
\t\tUAX29GraphemeBreakProperty(rawValue: lookup(scalar, in: graphemeBreakPropertyRanges)) ?? .other
\t}

\tstatic func indicConjunctBreak(for scalar: UInt32) -> UAX29IndicConjunctBreak {
\t\tUAX29IndicConjunctBreak(rawValue: lookup(scalar, in: indicConjunctBreakRanges)) ?? .none
\t}

\tstatic func isExtendedPictographic(_ scalar: UInt32) -> Bool {
\t\tlookup(scalar, in: extendedPictographicRanges) != 0
\t}

\tprivate static func lookup(_ scalar: UInt32, in ranges: [RangeRecord]) -> UInt8 {
\t\tvar lower = 0
\t\tvar upper = ranges.count
\t\twhile lower < upper {
\t\t\tlet mid = lower + (upper - lower) / 2
\t\t\tlet range = ranges[mid]
\t\t\tif scalar < range.lower {
\t\t\t\tupper = mid
\t\t\t} else if scalar > range.upper {
\t\t\t\tlower = mid + 1
\t\t\t} else {
\t\t\t\treturn range.value
\t\t\t}
\t\t}
\t\treturn 0
\t}
""")
emitRanges("graphemeBreakPropertyRanges", graphemeRanges, values: graphemeValues)
emitRanges("extendedPictographicRanges", extendedPictographicRanges, values: ["Extended_Pictographic": 1])
emitRanges("indicConjunctBreakRanges", indicRanges, values: indicValues)
print("}")
