#!/usr/bin/env swift
import Foundation

struct Binding {
	let line: Int
	let mode: String
	let key: String
	let commandID: String
}

let repo = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
let input = repo.appendingPathComponent("Sources/ItsyKeymap/Resources/keys.vim.toml")
let output = repo.appendingPathComponent("Tests/ItsyVimTests/GeneratedVimBindingTests.swift")

func fail(_ message: String) -> Never {
	FileHandle.standardError.write(Data((message + "\n").utf8))
	exit(EXIT_FAILURE)
}

func stripComment(_ line: String) -> String {
	var escaped = false
	var quoted = false
	var result = ""
	for character in line {
		if escaped {
			result.append(character)
			escaped = false
			continue
		}
		if character == "\\" {
			result.append(character)
			escaped = true
			continue
		}
		if character == "\"" {
			result.append(character)
			quoted.toggle()
			continue
		}
		if character == "#", !quoted {
			break
		}
		result.append(character)
	}
	return result.trimmingCharacters(in: .whitespaces)
}

func firstEqualsOutsideQuotes(in line: String) -> String.Index? {
	var escaped = false
	var quoted = false
	for index in line.indices {
		let character = line[index]
		if escaped {
			escaped = false
			continue
		}
		if character == "\\" {
			escaped = true
			continue
		}
		if character == "\"" {
			quoted.toggle()
			continue
		}
		if character == "=", !quoted {
			return index
		}
	}
	return nil
}

func parseQuoted(_ value: String) -> String? {
	guard value.count >= 2, value.first == "\"", value.last == "\"" else {
		return nil
	}
	var result = ""
	var escaped = false
	for character in value.dropFirst().dropLast() {
		if escaped {
			switch character {
			case "n":
				result.append("\n")
			case "t":
				result.append("\t")
			default:
				result.append(character)
			}
			escaped = false
			continue
		}
		if character == "\\" {
			escaped = true
		} else {
			result.append(character)
		}
	}
	return escaped ? nil : result
}

func swiftString(_ value: String) -> String {
	var result = "\""
	for scalar in value.unicodeScalars {
		switch scalar {
		case "\\":
			result += "\\\\"
		case "\"":
			result += "\\\""
		case "\n":
			result += "\\n"
		case "\t":
			result += "\\t"
		default:
			result.unicodeScalars.append(scalar)
		}
	}
	result += "\""
	return result
}

do {
	let contents = try String(contentsOf: input, encoding: .utf8)
	var mode: String?
	var bindings: [Binding] = []
	for (offset, rawLine) in contents.split(separator: "\n", omittingEmptySubsequences: false).enumerated() {
		let lineNumber = offset + 1
		let line = stripComment(String(rawLine))
		guard !line.isEmpty else {
			continue
		}
		if line.hasPrefix("[mode."), line.hasSuffix("]") {
			mode = String(line.dropFirst("[mode.".count).dropLast())
			continue
		}
		guard let currentMode = mode else {
			fail("\(input.path):\(lineNumber): binding outside mode")
		}
		guard let equals = firstEqualsOutsideQuotes(in: line),
		      let key = parseQuoted(line[..<equals].trimmingCharacters(in: .whitespaces)),
		      let commandID = parseQuoted(line[line.index(after: equals)...].trimmingCharacters(in: .whitespaces))
		else {
			fail("\(input.path):\(lineNumber): invalid binding")
		}
		bindings.append(Binding(line: lineNumber, mode: currentMode, key: key, commandID: commandID))
	}

	var lines = [
		"// generated by scripts/gen_vim_binding_tests.swift from Sources/ItsyKeymap/Resources/keys.vim.toml. do not edit.",
		"import AppKit",
		"import ItsyKeymap",
		"import ItsyVim",
		"import Testing",
		"",
		"private let generatedVimBindingCases: [GeneratedVimBindingCase] = [",
	]
	for binding in bindings {
		lines.append("\tGeneratedVimBindingCase(line: \(binding.line), mode: .\(binding.mode), key: \(swiftString(binding.key)), commandID: \(swiftString(binding.commandID))),")
	}
	lines += [
		"]",
		"",
	]
	let supportURL = repo.appendingPathComponent("scripts/vim_binding_regression_support.swift.txt")
	let support = try String(contentsOf: supportURL, encoding: .utf8)
	lines.append(support)
	try FileManager.default.createDirectory(at: output.deletingLastPathComponent(), withIntermediateDirectories: true)
	try lines.joined(separator: "\n").write(to: output, atomically: true, encoding: .utf8)
	print("Generated \(bindings.count) Vim binding cases at \(output.path)")
} catch {
	fail("\(error)")
}
