[mode.emacs]
"C-f" = "editor.moveRight"
"C-b" = "editor.moveLeft"
"C-n" = "editor.moveDown"
"C-p" = "editor.moveUp"
"C-a" = "editor.moveLineStart"
"C-e" = "editor.moveLineEnd"
"M-f" = "editor.moveWordForward"
"M-b" = "editor.moveWordBackward"
"M-<" = "editor.moveBufferStart"
"M->" = "editor.moveBufferEnd"
"C-w" = "emacs.killRegion"
"M-w" = "emacs.copyRegion"
"C-y" = "emacs.yank"
"M-y" = "emacs.yankPop"
"Cmd-D" = "editor.addNextSelection"
"C-s" = "emacs.isearchForward"
"C-r" = "emacs.isearchBackward"
"C-x C-s" = "file.save"
"C-x C-f" = "file.open"
"C-x b" = "file.nextBuffer"
"C-x k" = "file.close"
"C-x 0" = "pane.close"
"C-x 1" = "pane.closeOthers"
"C-x 2" = "pane.splitHorizontal"
"C-x 3" = "pane.splitVertical"
