[mode.emacs]
"C-f" = "editor.moveRight"
"C-b" = "editor.moveLeft"
"C-n" = "editor.moveDown"
"C-p" = "editor.moveUp"
"C-a" = "editor.moveLineStart"
"C-e" = "editor.moveLineEnd"
"M-f" = "editor.moveWordForward"
"M-b" = "editor.moveWordBackward"
"M-<" = "editor.moveBufferStart"
"M->" = "editor.moveBufferEnd"
"C-w" = "emacs.killRegion"
"M-w" = "emacs.copyRegion"
"C-y" = "emacs.yank"
"M-y" = "emacs.yankPop"
"C-s" = "edit.find"
"C-r" = "edit.findPrevious"
"C-x C-s" = "file.save"
"C-x C-f" = "file.open"
