[mode.normal]
"h" = "editor.moveLeft"
"j" = "editor.moveDown"
"k" = "editor.moveUp"
"l" = "editor.moveRight"
"w" = "editor.moveWordForward"
"Shift-W" = "editor.moveBigWordForward"
"b" = "editor.moveWordBackward"
"Shift-B" = "editor.moveBigWordBackward"
"e" = "editor.moveWordEnd"
"Shift-E" = "editor.moveBigWordEnd"
"0" = "editor.moveLineStart"
"Shift-6" = "editor.moveLineStart"
"Shift-4" = "editor.moveLineEnd"
"gg" = "editor.moveBufferStart"
"Shift-G" = "editor.moveBufferEnd"
"Shift-[" = "editor.moveParagraphBackward"
"Shift-]" = "editor.moveParagraphForward"
"f" = "editor.findCharForward"
"Shift-F" = "editor.findCharBackward"
"t" = "editor.tillCharForward"
"Shift-T" = "editor.tillCharBackward"
";" = "editor.repeatCharFind"
"," = "editor.repeatCharFindReverse"
"i" = "mode.insert"
"/" = "edit.find"

[mode.insert]
"Esc" = "mode.normal"
"jk" = "mode.normal"
