#ifndef INCLUDE_features_h__
#define INCLUDE_features_h__

#define GIT_THREADS 1
#define GIT_ARCH_64 1
#define GIT_USE_ICONV 1
#define GIT_USE_NSEC 1
#define GIT_USE_STAT_MTIMESPEC 1
#define GIT_USE_FUTIMENS 1
#define GIT_REGEX_BUILTIN 1
#define GIT_HTTPS 1
#define GIT_SECURE_TRANSPORT 1
#define GIT_HTTPPARSER_BUILTIN 1
#define GIT_SHA1_COMMON_CRYPTO 1
#define GIT_SHA256_COMMON_CRYPTO 1
#define GIT_COMPRESSION_BUILTIN 1
#define GIT_RAND_GETLOADAVG 1
#define GIT_IO_POLL 1
#define GIT_IO_SELECT 1
#define GIT_QSORT_BSD 1

#endif
